# Store texts, group C: Arabic, Hebrew, Hindi, Thai, Vietnamese, Indonesian,
# Malay, Japanese, Korean, Chinese. No dashes as punctuation (house rule).
# Thai uses spaces where other languages use periods.

AR = dict(
    name="Pixi: سنتي بالبكسلات",
    subtitle="متتبع المزاج ومذكرات يومية",
    keywords="مشاعر,يوميات,مذكرات,عادات,تقويم,قطة,نوم,دورة,أحلام,ألوان,mood,diary",
    promo="سؤال واحد كل صباح، ولون واحد لكل يوم. شاهد سنتك تتحول إلى صورة مضيئة مع Pixi، القطة الصغيرة التي تسألك كيف كان يومك أمس.",
    intro="سنتك كلها في صورة واحدة. سؤال واحد كل صباح، ولون واحد لكل يوم. بعد بضعة أسابيع سترى ما الذي يشكّل أيامك حقًا.",
    about="Pixi متتبع للمزاج على طريقة «Year in Pixels» مع قطة صغيرة مرسومة تسألك كيف كان يومك أمس. اضغط على لون وانتهى الأمر. يصبح كل يوم بكسلًا، وتصبح كل سنة صورة مضيئة تحب النظر إليها.",
    h_q="سؤال واحد، 15 ثانية",
    q=["تذكير لطيف كل صباح", "اضغط على لون. بلا كتابة وبلا ضغط", "فاتك يوم؟ أضفه لاحقًا"],
    h_t="أكثر من مجرد المزاج",
    t=["قوالب للمزاج والنوم والأحلام والطاقة والدورة الشهرية والألم والتمرين والكحول والتأمل والقراءة والماء ووقت الشاشة والامتنان وغيرها",
       "أو أنشئ خريطتك الخاصة بسؤالك وألوانك ومستوياتك"],
    h_s="اكتشف ما يرتبط ببعضه",
    s=["يُظهر Pixi الألوان التي تظهر معًا، مثل الليالي المريحة والأيام المشرقة",
       "شهرك مقارنة بالشهر الماضي، وما يلفت النظر في كل يوم من أيام الأسبوع"],
    h_p="سنتك كملصق",
    p=["كل خريطة كعجلة سنوية دائرية، للمشاركة أو لتعليقها على الحائط"],
    h_priv="الخصوصية أولًا",
    priv=["بلا حساب وبلا إعلانات. تبقى إدخالاتك على جهازك"],
    h_prem="PIXI PREMIUM",
    prem1="Pixi مجاني حتى 4 خرائط. يفتح Pixi Premium عددًا غير محدود من الخرائط وجميع الإحصاءات: جرّب الاشتراك الشهري مجانًا لمدة 3 أيام، أو ادفع مرة واحدة للوصول مدى الحياة.",
    prem2="يتجدد الاشتراك الشهري تلقائيًا ما لم يتم إلغاؤه قبل 24 ساعة على الأقل من نهاية الفترة الحالية. يتم تحصيل الدفع من حساب Apple الخاص بك. يمكنك إدارة الاشتراك أو إلغاؤه من إعدادات حسابك في App Store.",
    terms="شروط الاستخدام",
    privacy="سياسة الخصوصية",
    contact="أسئلة أو أفكار؟ كاسبار، المطوّر، يقرأ كل رسالة:",
)

HE = dict(
    name="Pixi: השנה שלי בפיקסלים",
    subtitle="מעקב מצב רוח ויומן יומי",
    keywords="רגשות,יומן,הרגלים,לוח שנה,חתול,חמוד,שינה,מחזור,חלומות,צבעים,mood,diary",
    promo="שאלה אחת בכל בוקר, צבע אחד לכל יום. צפו איך השנה שלכם הופכת לתמונה זוהרת עם Pixi, החתול הקטן ששואל איך היה אתמול.",
    intro="כל השנה שלכם בתמונה אחת. שאלה אחת בכל בוקר, צבע אחד לכל יום. אחרי כמה שבועות תראו מה באמת מעצב את הימים שלכם.",
    about="Pixi הוא מעקב מצב רוח בסגנון \"Year in Pixels\" עם חתול קטן מצויר ששואל איך היה אתמול. הקישו על צבע, וזהו. כל יום הופך לפיקסל, כל שנה לתמונה זוהרת שכיף להסתכל עליה.",
    h_q="שאלה אחת, 15 שניות",
    q=["תזכורת עדינה בכל בוקר", "הקישו על צבע. בלי להקליד, בלי לחץ", "פספסתם יום? אפשר להשלים אחר כך"],
    h_t="יותר ממצב רוח",
    t=["תבניות למצב רוח, שינה, חלומות, אנרגיה, מחזור, כאב, אימונים, אלכוהול, מדיטציה, קריאה, מים, זמן מסך, הכרת תודה ועוד",
       "או צרו מפה משלכם עם שאלה, צבעים ורמות משלכם"],
    h_s="גלו מה הולך ביחד",
    s=["Pixi מראה אילו צבעים מופיעים יחד, כמו לילות מרגיעים וימים זוהרים",
       "החודש שלכם בהשוואה לקודם, ומה בולט בכל יום בשבוע"],
    h_p="השנה שלכם כפוסטר",
    p=["כל מפה כגלגל שנה עגול, לשיתוף או לתלייה על הקיר"],
    h_priv="פרטיות מובנית",
    priv=["בלי חשבון, בלי פרסומות. הרשומות שלכם נשארות במכשיר"],
    h_prem="PIXI PREMIUM",
    prem1="Pixi חינמי עם עד 4 מפות. Pixi Premium פותח מפות ללא הגבלה ואת כל הסטטיסטיקות: נסו את המנוי החודשי בחינם למשך 3 ימים, או שלמו פעם אחת לגישה לכל החיים.",
    prem2="המנוי החודשי מתחדש אוטומטית, אלא אם בוטל לפחות 24 שעות לפני סוף התקופה הנוכחית. התשלום מחויב בחשבון Apple שלכם. ניתן לנהל או לבטל אותו בהגדרות חשבון App Store שלכם.",
    terms="תנאי שימוש",
    privacy="מדיניות פרטיות",
    contact="שאלות או רעיונות? קספר, המפתח, קורא כל הודעה:",
)

HI = dict(
    name="Pixi: पिक्सल में मेरा साल",
    subtitle="मूड ट्रैकर और डेली डायरी",
    keywords="mood,diary,journal,cat,sleep,भावनाएं,डायरी,बिल्ली,नींद,सपने",
    promo="हर सुबह एक सवाल, हर दिन एक रंग। देखिए कैसे आपका साल एक चमकती तस्वीर बन जाता है, Pixi के साथ, वह छोटी बिल्ली जो पूछती है कि कल कैसा था।",
    intro="आपका पूरा साल एक तस्वीर में। हर सुबह एक सवाल, हर दिन एक रंग। कुछ हफ्तों बाद आप देखेंगे कि आपके दिनों को असल में क्या आकार देता है।",
    about="Pixi एक \"Year in Pixels\" मूड ट्रैकर है, जिसमें एक छोटी सी स्केच की हुई बिल्ली आपसे पूछती है कि कल कैसा था। एक रंग पर टैप करें, बस हो गया। हर दिन एक पिक्सल बनता है, हर साल एक चमकती तस्वीर जिसे देखना आपको अच्छा लगेगा।",
    h_q="एक सवाल, 15 सेकंड",
    q=["हर सुबह एक प्यारा सा रिमाइंडर", "एक रंग पर टैप करें। न लिखना, न कोई दबाव", "कोई दिन छूट गया? बाद में भर लें"],
    h_t="मूड से कहीं ज़्यादा",
    t=["मूड, नींद, सपने, ऊर्जा, पीरियड, दर्द, ट्रेनिंग, शराब, ध्यान, पढ़ना, पानी, स्क्रीन टाइम, कृतज्ञता और बहुत कुछ के लिए टेम्पलेट",
       "या अपना खुद का मैप बनाएं, अपने सवाल, रंगों और स्तरों के साथ"],
    h_s="देखें क्या साथ चलता है",
    s=["Pixi दिखाता है कि कौन से रंग साथ में आते हैं, जैसे सुकून भरी रातें और खिले हुए दिन",
       "आपका महीना पिछले महीने की तुलना में, और हफ्ते के किस दिन क्या खास दिखता है"],
    h_p="आपका साल एक पोस्टर की तरह",
    p=["हर मैप एक गोल सालाना पहिये के रूप में, शेयर करने या दीवार पर लगाने के लिए"],
    h_priv="पूरी तरह निजी",
    priv=["न अकाउंट, न विज्ञापन। आपकी एंट्री आपके डिवाइस पर ही रहती हैं"],
    h_prem="PIXI PREMIUM",
    prem1="Pixi 4 मैप तक मुफ्त है। Pixi Premium से असीमित मैप और सभी आंकड़े अनलॉक होते हैं: मासिक प्लान को 3 दिन मुफ्त आज़माएं, या एक बार भुगतान करके हमेशा के लिए पाएं।",
    prem2="मासिक सब्सक्रिप्शन अपने आप रिन्यू होता है, जब तक कि मौजूदा अवधि खत्म होने से कम से कम 24 घंटे पहले इसे रद्द न किया जाए। भुगतान आपके Apple अकाउंट से लिया जाता है। आप इसे अपनी App Store अकाउंट सेटिंग्स में मैनेज या रद्द कर सकते हैं।",
    terms="उपयोग की शर्तें",
    privacy="गोपनीयता नीति",
    contact="सवाल या आइडिया? डेवलपर Caspar हर मैसेज पढ़ते हैं:",
)

TH = dict(
    name="Pixi: ปีของฉันเป็นพิกเซล",
    subtitle="บันทึกอารมณ์และไดอารี่รายวัน",
    keywords="mood,diary,อารมณ์,ไดอารี่,แมว,นอน,ความฝัน,ปฏิทิน,นิสัย",
    promo="หนึ่งคำถามทุกเช้า หนึ่งสีต่อวัน ดูปีของคุณกลายเป็นภาพที่เปล่งประกายไปกับ Pixi แมวตัวน้อยที่ถามว่าเมื่อวานเป็นอย่างไร",
    intro="ทั้งปีของคุณในภาพเดียว หนึ่งคำถามทุกเช้า หนึ่งสีต่อวัน ผ่านไปไม่กี่สัปดาห์ คุณจะเห็นว่าอะไรที่กำหนดวันของคุณจริงๆ",
    about="Pixi คือแอปบันทึกอารมณ์แบบ \"Year in Pixels\" กับแมวตัวน้อยลายเส้นที่ถามว่าเมื่อวานเป็นอย่างไร แตะสีเดียวก็เสร็จ ทุกวันกลายเป็นหนึ่งพิกเซล ทุกปีกลายเป็นภาพที่เปล่งประกายซึ่งคุณอยากดูซ้ำแล้วซ้ำเล่า",
    h_q="หนึ่งคำถาม 15 วินาที",
    q=["การแจ้งเตือนอย่างอ่อนโยนทุกเช้า", "แตะสี ไม่ต้องพิมพ์ ไม่มีแรงกดดัน", "ลืมบันทึกไปหนึ่งวัน? เติมย้อนหลังได้"],
    h_t="ติดตามได้มากกว่าอารมณ์",
    t=["เทมเพลตสำหรับอารมณ์ การนอน ความฝัน พลังงาน ประจำเดือน ความเจ็บปวด การออกกำลังกาย แอลกอฮอล์ การทำสมาธิ การอ่าน การดื่มน้ำ เวลาหน้าจอ ความรู้สึกขอบคุณ และอื่นๆ",
       "หรือสร้างแผนที่ของคุณเองด้วยคำถาม สี และระดับของคุณเอง"],
    h_s="ดูว่าอะไรไปด้วยกัน",
    s=["Pixi แสดงให้เห็นว่าสีไหนมักปรากฏพร้อมกัน เช่น คืนที่หลับสบายกับวันที่สดใส",
       "เดือนนี้เทียบกับเดือนที่แล้ว และสิ่งที่โดดเด่นในแต่ละวันของสัปดาห์"],
    h_p="ปีของคุณเป็นโปสเตอร์",
    p=["ทุกแผนที่เป็นวงล้อรายปีทรงกลม สำหรับแชร์หรือแขวนบนผนัง"],
    h_priv="เป็นส่วนตัวตั้งแต่ต้น",
    priv=["ไม่ต้องมีบัญชี ไม่มีโฆษณา ข้อมูลของคุณอยู่ในอุปกรณ์ของคุณเท่านั้น"],
    h_prem="PIXI PREMIUM",
    prem1="Pixi ใช้ฟรีได้สูงสุด 4 แผนที่ Pixi Premium ปลดล็อกแผนที่ไม่จำกัดและสถิติทั้งหมด: ทดลองแผนรายเดือนฟรี 3 วัน หรือจ่ายครั้งเดียวใช้ได้ตลอดชีพ",
    prem2="การสมัครสมาชิกรายเดือนจะต่ออายุโดยอัตโนมัติ เว้นแต่จะยกเลิกอย่างน้อย 24 ชั่วโมงก่อนสิ้นสุดรอบปัจจุบัน ระบบจะเรียกเก็บเงินจากบัญชี Apple ของคุณ คุณสามารถจัดการหรือยกเลิกได้ในการตั้งค่าบัญชี App Store ของคุณ",
    terms="ข้อกำหนดการใช้งาน",
    privacy="นโยบายความเป็นส่วนตัว",
    contact="มีคำถามหรือไอเดีย? Caspar ผู้พัฒนาอ่านทุกข้อความ:",
)

VI = dict(
    name="Pixi: Năm của tôi bằng pixel",
    subtitle="Nhật ký cảm xúc mỗi ngày",
    keywords="tâm trạng,cảm xúc,nhật ký,thói quen,lịch,mèo,dễ thương,giấc ngủ,giấc mơ,màu sắc,mood",
    promo="Mỗi sáng một câu hỏi, mỗi ngày một màu. Ngắm năm của bạn trở thành một bức tranh rực rỡ cùng Pixi, chú mèo nhỏ luôn hỏi hôm qua của bạn thế nào.",
    intro="Cả năm của bạn trong một bức tranh. Mỗi sáng một câu hỏi, mỗi ngày một màu. Sau vài tuần, bạn sẽ thấy điều gì thực sự định hình những ngày của mình.",
    about="Pixi là ứng dụng theo dõi tâm trạng kiểu \"Year in Pixels\" với một chú mèo nhỏ vẽ tay hỏi bạn hôm qua thế nào. Chạm vào một màu là xong. Mỗi ngày thành một pixel, mỗi năm thành một bức tranh rực rỡ mà bạn thích ngắm nhìn.",
    h_q="MỘT CÂU HỎI, 15 GIÂY",
    q=["Lời nhắc nhẹ nhàng mỗi sáng", "Chạm vào một màu. Không cần gõ, không áp lực", "Lỡ một ngày? Điền bù sau cũng được"],
    h_t="KHÔNG CHỈ LÀ TÂM TRẠNG",
    t=["Mẫu cho tâm trạng, giấc ngủ, giấc mơ, năng lượng, kỳ kinh, cơn đau, tập luyện, rượu bia, thiền, đọc sách, uống nước, thời gian dùng màn hình, lòng biết ơn và nhiều hơn nữa",
       "Hoặc tạo bản đồ riêng với câu hỏi, màu sắc và mức độ của riêng bạn"],
    h_s="THẤY ĐIỀU GÌ ĐI CÙNG NHAU",
    s=["Pixi cho thấy những màu nào thường xuất hiện cùng nhau, như những đêm ngon giấc và những ngày rạng rỡ",
       "Tháng này so với tháng trước, và điều gì nổi bật vào từng ngày trong tuần"],
    h_p="NĂM CỦA BẠN THÀNH POSTER",
    p=["Mỗi bản đồ là một vòng tròn năm, để chia sẻ hoặc treo lên tường"],
    h_priv="RIÊNG TƯ TỪ ĐẦU",
    priv=["Không tài khoản, không quảng cáo. Dữ liệu của bạn nằm trên thiết bị của bạn"],
    h_prem="PIXI PREMIUM",
    prem1="Pixi miễn phí với tối đa 4 bản đồ. Pixi Premium mở khóa bản đồ không giới hạn và toàn bộ thống kê: dùng thử gói tháng miễn phí 3 ngày, hoặc trả một lần để dùng trọn đời.",
    prem2="Gói đăng ký hàng tháng tự động gia hạn trừ khi được hủy ít nhất 24 giờ trước khi kết thúc kỳ hiện tại. Khoản thanh toán được tính vào Tài khoản Apple của bạn. Bạn có thể quản lý hoặc hủy trong phần cài đặt tài khoản App Store.",
    terms="Điều khoản sử dụng",
    privacy="Chính sách quyền riêng tư",
    contact="Có câu hỏi hoặc ý tưởng? Caspar, nhà phát triển, đọc mọi tin nhắn:",
)

ID = dict(
    name="Pixi: Tahunku dalam Piksel",
    subtitle="Pelacak Mood & Jurnal Harian",
    keywords="suasana hati,perasaan,emosi,diari,kebiasaan,kalender,kucing,lucu,tidur,haid,mimpi,warna,estetik",
    promo="Satu pertanyaan setiap pagi, satu warna setiap hari. Lihat tahunmu menjadi gambar yang bercahaya bersama Pixi, kucing kecil yang bertanya bagaimana harimu kemarin.",
    intro="Setahun penuh dalam satu gambar. Satu pertanyaan setiap pagi, satu warna setiap hari. Setelah beberapa minggu, kamu akan melihat apa yang benar-benar membentuk hari-harimu.",
    about="Pixi adalah pelacak mood bergaya \"Year in Pixels\" dengan kucing kecil bergambar tangan yang bertanya bagaimana harimu kemarin. Ketuk satu warna, selesai. Setiap hari menjadi satu piksel, setiap tahun menjadi gambar bercahaya yang senang kamu pandangi.",
    h_q="SATU PERTANYAAN, 15 DETIK",
    q=["Pengingat lembut setiap pagi", "Ketuk satu warna. Tanpa mengetik, tanpa tekanan", "Terlewat sehari? Isi nanti saja"],
    h_t="LEBIH DARI SEKADAR MOOD",
    t=["Template untuk mood, tidur, mimpi, energi, haid, nyeri, olahraga, alkohol, meditasi, membaca, minum air, waktu layar, rasa syukur, dan lainnya",
       "Atau buat peta sendiri dengan pertanyaan, warna, dan tingkatanmu sendiri"],
    h_s="LIHAT APA YANG SALING BERKAITAN",
    s=["Pixi menunjukkan warna mana yang sering muncul bersamaan, seperti malam yang nyenyak dan hari yang cerah",
       "Bulan ini dibandingkan bulan lalu, dan apa yang menonjol di setiap hari dalam seminggu"],
    h_p="TAHUNMU SEBAGAI POSTER",
    p=["Setiap peta sebagai roda tahunan yang bulat, untuk dibagikan atau dipajang di dinding"],
    h_priv="PRIVAT SEJAK AWAL",
    priv=["Tanpa akun, tanpa iklan. Catatanmu tetap di perangkatmu"],
    h_prem="PIXI PREMIUM",
    prem1="Pixi gratis hingga 4 peta. Pixi Premium membuka peta tanpa batas dan semua statistik: coba paket bulanan gratis selama 3 hari, atau bayar sekali untuk akses seumur hidup.",
    prem2="Langganan bulanan diperpanjang secara otomatis kecuali dibatalkan paling lambat 24 jam sebelum akhir periode saat ini. Pembayaran ditagihkan ke Akun Apple kamu. Kamu dapat mengelola atau membatalkannya di pengaturan akun App Store.",
    terms="Ketentuan Penggunaan",
    privacy="Kebijakan Privasi",
    contact="Punya pertanyaan atau ide? Caspar, sang pengembang, membaca setiap pesan:",
)

MS = dict(
    name="Pixi: Tahun Saya dalam Piksel",
    subtitle="Penjejak Mood & Jurnal Harian",
    keywords="emosi,perasaan,diari,tabiat,kalendar,kucing,comel,tidur,haid,mimpi,warna,estetik,jurnal",
    promo="Satu soalan setiap pagi, satu warna setiap hari. Lihat tahun anda menjadi gambar yang bercahaya bersama Pixi, kucing kecil yang bertanya bagaimana hari anda semalam.",
    intro="Setahun penuh dalam satu gambar. Satu soalan setiap pagi, satu warna setiap hari. Selepas beberapa minggu, anda akan nampak apa yang benar-benar membentuk hari-hari anda.",
    about="Pixi ialah penjejak mood gaya \"Year in Pixels\" dengan seekor kucing kecil lakaran tangan yang bertanya bagaimana hari anda semalam. Ketik satu warna, siap. Setiap hari menjadi satu piksel, setiap tahun menjadi gambar bercahaya yang anda suka tatap.",
    h_q="SATU SOALAN, 15 SAAT",
    q=["Peringatan lembut setiap pagi", "Ketik satu warna. Tiada menaip, tiada tekanan", "Terlepas sehari? Isi kemudian"],
    h_t="LEBIH DARIPADA MOOD",
    t=["Templat untuk mood, tidur, mimpi, tenaga, haid, sakit, latihan, alkohol, meditasi, membaca, air, masa skrin, rasa syukur dan banyak lagi",
       "Atau cipta peta sendiri dengan soalan, warna dan tahap anda sendiri"],
    h_s="LIHAT APA YANG BERKAIT",
    s=["Pixi menunjukkan warna yang sering muncul bersama, seperti malam yang lena dan hari yang ceria",
       "Bulan ini berbanding bulan lepas, dan apa yang menonjol pada setiap hari dalam minggu"],
    h_p="TAHUN ANDA SEBAGAI POSTER",
    p=["Setiap peta sebagai roda tahunan bulat, untuk dikongsi atau digantung di dinding"],
    h_priv="PERIBADI SEJAK AWAL",
    priv=["Tiada akaun, tiada iklan. Catatan anda kekal dalam peranti anda"],
    h_prem="PIXI PREMIUM",
    prem1="Pixi percuma sehingga 4 peta. Pixi Premium membuka peta tanpa had dan semua statistik: cuba pelan bulanan secara percuma selama 3 hari, atau bayar sekali untuk akses seumur hidup.",
    prem2="Langganan bulanan diperbaharui secara automatik melainkan dibatalkan sekurang-kurangnya 24 jam sebelum tamat tempoh semasa. Bayaran dicaj ke Akaun Apple anda. Anda boleh mengurus atau membatalkannya dalam tetapan akaun App Store anda.",
    terms="Terma Penggunaan",
    privacy="Dasar Privasi",
    contact="Ada soalan atau idea? Caspar, pembangun apl ini, membaca setiap mesej:",
)

JA = dict(
    name="Pixi: ピクセルで綴る私の1年",
    subtitle="気分トラッカーと毎日の日記",
    keywords="気分,感情,日記,習慣,カレンダー,猫,かわいい,睡眠,生理,夢,色,メンタル",
    promo="毎朝ひとつの質問、毎日ひとつの色。昨日はどうだった？と聞いてくれる小さな猫Pixiと一緒に、あなたの1年が輝く1枚の絵になっていきます。",
    intro="あなたの1年を1枚の絵に。毎朝ひとつの質問、毎日ひとつの色。数週間たつと、あなたの毎日を本当に形づくっているものが見えてきます。",
    about="Pixiは「Year in Pixels」スタイルの気分トラッカー。手描きの小さな猫が、昨日はどうだったかを聞いてくれます。色をタップするだけで完了。毎日がひとつのピクセルになり、1年は眺めたくなる輝く1枚の絵になります。",
    h_q="質問はひとつ、15秒",
    q=["毎朝やさしくお知らせ", "色をタップするだけ。入力もプレッシャーもなし", "記録し忘れた日も、あとから入力できます"],
    h_t="気分だけじゃない",
    t=["気分、睡眠、夢、エネルギー、生理、痛み、トレーニング、お酒、瞑想、読書、水分、スクリーンタイム、感謝などのテンプレート",
       "自分だけの質問、色、段階でオリジナルのマップも作れます"],
    h_s="つながりが見える",
    s=["ぐっすり眠れた夜と輝く日のように、一緒に現れる色をPixiが教えてくれます",
       "今月と先月の比較、そして曜日ごとの傾向"],
    h_p="1年をポスターに",
    p=["すべてのマップを丸い年間ホイールに。シェアしたり、壁に飾ったり"],
    h_priv="プライバシーを大切に",
    priv=["アカウント不要、広告なし。記録はあなたのデバイスの中だけに保存されます"],
    h_prem="PIXI PREMIUM",
    prem1="Pixiはマップ4つまで無料。Pixi Premiumならマップ無制限で、すべての統計が使えます。月額プランは3日間無料でお試しいただけます。買い切りでずっと使うこともできます。",
    prem2="月額サブスクリプションは、現在の期間が終了する24時間以上前にキャンセルしない限り、自動的に更新されます。お支払いはApple Accountに請求されます。App Storeのアカウント設定から管理またはキャンセルできます。",
    terms="利用規約",
    privacy="プライバシーポリシー",
    contact="ご質問やアイデアはありますか？開発者のCasparがすべてのメッセージを読んでいます：",
)

KO = dict(
    name="Pixi: 픽셀로 채우는 나의 1년",
    subtitle="무드 트래커 & 하루 일기",
    keywords="기분,감정,일기,다이어리,습관,캘린더,고양이,귀여운,수면,생리,꿈,색깔,기록",
    promo="매일 아침 질문 하나, 하루에 색 하나. 어제는 어땠는지 물어보는 작은 고양이 Pixi와 함께 당신의 1년이 빛나는 한 장의 그림이 되어 가요.",
    intro="당신의 1년을 한 장의 그림으로. 매일 아침 질문 하나, 하루에 색 하나. 몇 주만 지나면 무엇이 당신의 하루를 만들어 가는지 보이기 시작해요.",
    about="Pixi는 \"Year in Pixels\" 스타일의 무드 트래커예요. 손으로 그린 작은 고양이가 어제는 어땠는지 물어봐요. 색을 탭하면 끝. 하루하루가 하나의 픽셀이 되고, 1년은 자꾸 보고 싶은 빛나는 그림이 돼요.",
    h_q="질문 하나, 15초",
    q=["매일 아침 부드러운 알림", "색을 탭하기만 하면 돼요. 입력도 부담도 없어요", "하루를 놓쳤나요? 나중에 채우면 돼요"],
    h_t="기분 그 이상을 기록해요",
    t=["기분, 수면, 꿈, 에너지, 생리, 통증, 운동, 음주, 명상, 독서, 물, 스크린 타임, 감사 등 다양한 템플릿",
       "나만의 질문, 색, 단계로 직접 맵을 만들 수도 있어요"],
    h_s="함께 나타나는 것을 발견해요",
    s=["푹 잔 밤과 빛나는 하루처럼 함께 나타나는 색을 Pixi가 보여줘요",
       "지난달과 비교한 이번 달, 그리고 요일마다 눈에 띄는 점"],
    h_p="나의 1년을 포스터로",
    p=["모든 맵을 둥근 연간 휠로. 공유하거나 벽에 걸어 보세요"],
    h_priv="처음부터 프라이빗하게",
    priv=["계정도 광고도 없어요. 기록은 당신의 기기에만 저장돼요"],
    h_prem="PIXI PREMIUM",
    prem1="Pixi는 최대 4개의 맵까지 무료예요. Pixi Premium은 무제한 맵과 모든 통계를 열어 줘요: 월간 플랜을 3일 동안 무료로 체험하거나, 한 번 결제로 평생 이용하세요.",
    prem2="월간 구독은 현재 기간이 끝나기 최소 24시간 전에 취소하지 않으면 자동으로 갱신됩니다. 결제는 Apple 계정으로 청구됩니다. App Store 계정 설정에서 관리하거나 취소할 수 있습니다.",
    terms="이용 약관",
    privacy="개인정보 처리방침",
    contact="질문이나 아이디어가 있나요? 개발자 Caspar가 모든 메시지를 읽어요:",
)

ZH_HANS = dict(
    name="Pixi: 用像素记录我的一年",
    subtitle="心情追踪与每日日记",
    keywords="心情,情绪,日记,手账,习惯,日历,猫咪,可爱,睡眠,经期,梦境,颜色,打卡",
    promo="每天早上一个问题，每天一种颜色。和会问你昨天过得怎么样的小猫 Pixi 一起，看你的一年变成一幅闪闪发光的画。",
    intro="你的一整年，尽在一幅画中。每天早上一个问题，每天一种颜色。几周之后，你就会看到真正塑造你每一天的是什么。",
    about="Pixi 是一款“Year in Pixels”风格的心情追踪应用，一只手绘小猫会问你昨天过得怎么样。点一下颜色，就完成了。每一天都变成一个像素，每一年都变成一幅让你爱不释手的发光画作。",
    h_q="一个问题，15 秒",
    q=["每天早上温柔提醒", "点一下颜色。无需打字，没有压力", "错过了一天？之后再补上"],
    h_t="不只是心情",
    t=["心情、睡眠、梦境、精力、经期、疼痛、训练、饮酒、冥想、阅读、喝水、屏幕使用时间、感恩等模板",
       "也可以用你自己的问题、颜色和等级创建专属地图"],
    h_s="看见彼此的关联",
    s=["Pixi 会告诉你哪些颜色经常一起出现，比如安稳的夜晚和明亮的日子",
       "本月与上月的对比，以及每周各天的特点"],
    h_p="把你的一年做成海报",
    p=["每张地图都能变成圆形年轮，可以分享，也可以挂在墙上"],
    h_priv="隐私至上",
    priv=["无需账号，没有广告。你的记录只保存在你的设备上"],
    h_prem="PIXI PREMIUM",
    prem1="Pixi 最多可免费使用 4 张地图。Pixi Premium 解锁无限地图和全部统计：月度方案可免费试用 3 天，也可以一次性购买，永久使用。",
    prem2="月度订阅会自动续订，除非在当前周期结束前至少 24 小时取消。费用将从你的 Apple 账户扣除。你可以在 App Store 账户设置中管理或取消订阅。",
    terms="使用条款",
    privacy="隐私政策",
    contact="有问题或想法？开发者 Caspar 会阅读每一条消息：",
)

ZH_HANT = dict(
    name="Pixi: 用像素記錄我的一年",
    subtitle="心情追蹤與每日日記",
    keywords="心情,情緒,日記,手帳,習慣,日曆,貓咪,可愛,睡眠,生理期,夢境,顏色,打卡",
    promo="每天早上一個問題，每天一種顏色。和會問你昨天過得如何的小貓 Pixi 一起，看你的一年變成一幅閃閃發光的畫。",
    intro="你的一整年，盡在一幅畫中。每天早上一個問題，每天一種顏色。幾週之後，你就會看到真正形塑你每一天的是什麼。",
    about="Pixi 是一款「Year in Pixels」風格的心情追蹤 App，一隻手繪小貓會問你昨天過得如何。點一下顏色，就完成了。每一天都變成一個像素，每一年都變成一幅讓你愛不釋手的發光畫作。",
    h_q="一個問題，15 秒",
    q=["每天早上溫柔提醒", "點一下顏色。不用打字，沒有壓力", "錯過了一天？之後再補上"],
    h_t="不只是心情",
    t=["心情、睡眠、夢境、精力、生理期、疼痛、訓練、飲酒、冥想、閱讀、喝水、螢幕使用時間、感恩等範本",
       "也可以用你自己的問題、顏色和等級建立專屬地圖"],
    h_s="看見彼此的關聯",
    s=["Pixi 會告訴你哪些顏色經常一起出現，例如安穩的夜晚和明亮的日子",
       "本月與上月的比較，以及每週各天的特點"],
    h_p="把你的一年做成海報",
    p=["每張地圖都能變成圓形年輪，可以分享，也可以掛在牆上"],
    h_priv="隱私至上",
    priv=["不需帳號，沒有廣告。你的記錄只儲存在你的裝置上"],
    h_prem="PIXI PREMIUM",
    prem1="Pixi 最多可免費使用 4 張地圖。Pixi Premium 解鎖無限地圖和所有統計：月訂方案可免費試用 3 天，也可以一次購買，永久使用。",
    prem2="月訂閱會自動續訂，除非在目前週期結束前至少 24 小時取消。費用將從你的 Apple 帳號扣款。你可以在 App Store 帳號設定中管理或取消訂閱。",
    terms="使用條款",
    privacy="隱私權政策",
    contact="有問題或想法嗎？開發者 Caspar 會閱讀每一則訊息：",
)

GROUP_C = {
    "ar-SA": AR, "he": HE, "hi": HI, "th": TH, "vi": VI, "id": ID, "ms": MS,
    "ja": JA, "ko": KO, "zh-Hans": ZH_HANS, "zh-Hant": ZH_HANT,
}
