# Store texts, group B: Nordic, Central and Eastern European languages, Greek, Turkish.
# No dashes as punctuation anywhere (house rule).

SV = dict(
    name="Pixi: Mitt år i pixlar",
    subtitle="Humördagbok och tracker",
    keywords="känslor,dagbok,vanor,kalender,katt,söt,sömn,mens,drömmar,färger,egenvård,mående,humör",
    promo="En fråga varje morgon, en färg varje dag. Se ditt år bli en lysande bild med Pixi, den lilla katten som frågar hur gårdagen var.",
    intro="Hela ditt år i en enda bild. En fråga varje morgon, en färg varje dag. Efter några veckor ser du vad som verkligen präglar dina dagar.",
    about="Pixi är en humörtracker i \"Year in Pixels\" stil med en liten tecknad katt som frågar hur gårdagen var. Tryck på en färg, klart. Varje dag blir en pixel, varje år en lysande bild som du gärna tittar på.",
    h_q="EN FRÅGA, 15 SEKUNDER",
    q=["En mjuk påminnelse varje morgon", "Tryck på en färg. Inget skrivande, ingen press", "Missat en dag? Fyll i den senare"],
    h_t="MER ÄN BARA HUMÖR",
    t=["Mallar för humör, sömn, drömmar, energi, mens, smärta, träning, alkohol, meditation, läsning, vatten, skärmtid, tacksamhet och mer",
       "Eller skapa din egen karta med egen fråga, egna färger och nivåer"],
    h_s="SE VAD SOM HÖR IHOP",
    s=["Pixi visar vilka färger som dyker upp tillsammans, som vilsamma nätter och strålande dagar",
       "Din månad jämförd med den förra, och vad som sticker ut på vilken veckodag"],
    h_p="DITT ÅR SOM AFFISCH",
    p=["Varje karta som ett runt årshjul, att dela eller hänga på väggen"],
    h_priv="PRIVAT FRÅN BÖRJAN",
    priv=["Inget konto, ingen reklam. Dina uppgifter stannar på din enhet"],
    h_prem="PIXI PREMIUM",
    prem1="Pixi är gratis med upp till 4 kartor. Pixi Premium låser upp obegränsat antal kartor och all statistik: prova månadsplanen gratis i 3 dagar eller betala en gång för livstidsåtkomst.",
    prem2="Månadsprenumerationen förnyas automatiskt om den inte sägs upp minst 24 timmar innan den aktuella perioden tar slut. Betalningen dras från ditt Apple-konto. Du kan hantera eller säga upp den i inställningarna för ditt App Store-konto.",
    terms="Användarvillkor",
    privacy="Integritetspolicy",
    contact="Frågor eller idéer? Caspar, utvecklaren, läser alla meddelanden:",
)

DA = dict(
    name="Pixi: Mit år i pixels",
    subtitle="Humørdagbog og tracker",
    keywords="følelser,dagbog,vaner,kalender,kat,sød,søvn,menstruation,drømme,farver,selvomsorg,trivsel",
    promo="Ét spørgsmål hver morgen, én farve om dagen. Se dit år blive til et lysende billede med Pixi, den lille kat, der spørger, hvordan i går var.",
    intro="Hele dit år i ét billede. Ét spørgsmål hver morgen, én farve om dagen. Efter et par uger ser du, hvad der virkelig præger dine dage.",
    about="Pixi er en humørtracker i \"Year in Pixels\" stil med en lille tegnet kat, der spørger, hvordan i går var. Tryk på en farve, færdig. Hver dag bliver en pixel, hvert år et lysende billede, du gerne ser på.",
    h_q="ÉT SPØRGSMÅL, 15 SEKUNDER",
    q=["En blid påmindelse hver morgen", "Tryk på en farve. Ingen skrivning, intet pres", "Glemt en dag? Udfyld den senere"],
    h_t="MERE END BARE HUMØR",
    t=["Skabeloner til humør, søvn, drømme, energi, menstruation, smerter, træning, alkohol, meditation, læsning, vand, skærmtid, taknemmelighed og mere",
       "Eller lav dit eget kort med dit eget spørgsmål, dine egne farver og niveauer"],
    h_s="SE HVAD DER HØRER SAMMEN",
    s=["Pixi viser, hvilke farver der dukker op sammen, som udhvilede nætter og strålende dage",
       "Din måned sammenlignet med den forrige, og hvad der skiller sig ud på hvilken ugedag"],
    h_p="DIT ÅR SOM PLAKAT",
    p=["Hvert kort som et rundt årshjul, til at dele eller hænge på væggen"],
    h_priv="PRIVAT FRA START",
    priv=["Ingen konto, ingen reklamer. Dine data bliver på din enhed"],
    h_prem="PIXI PREMIUM",
    prem1="Pixi er gratis med op til 4 kort. Pixi Premium låser op for ubegrænsede kort og al statistik: prøv månedsabonnementet gratis i 3 dage, eller betal én gang for livslang adgang.",
    prem2="Månedsabonnementet fornyes automatisk, medmindre det opsiges mindst 24 timer før udgangen af den aktuelle periode. Betalingen trækkes fra din Apple-konto. Du kan administrere eller opsige det i indstillingerne for din App Store-konto.",
    terms="Brugsvilkår",
    privacy="Privatlivspolitik",
    contact="Spørgsmål eller idéer? Caspar, udvikleren, læser alle beskeder:",
)

NO = dict(
    name="Pixi: Mitt år i piksler",
    subtitle="Humørdagbok og tracker",
    keywords="følelser,dagbok,vaner,kalender,katt,søt,søvn,mens,drømmer,farger,egenomsorg,trivsel",
    promo="Ett spørsmål hver morgen, én farge hver dag. Se året ditt bli et lysende bilde med Pixi, den lille katten som spør hvordan gårsdagen var.",
    intro="Hele året ditt i ett bilde. Ett spørsmål hver morgen, én farge hver dag. Etter noen uker ser du hva som virkelig preger dagene dine.",
    about="Pixi er en humørtracker i \"Year in Pixels\" stil med en liten tegnet katt som spør hvordan gårsdagen var. Trykk på en farge, ferdig. Hver dag blir en piksel, hvert år et lysende bilde du liker å se på.",
    h_q="ETT SPØRSMÅL, 15 SEKUNDER",
    q=["En mild påminnelse hver morgen", "Trykk på en farge. Ingen skriving, ikke noe press", "Gått glipp av en dag? Fyll den inn senere"],
    h_t="MER ENN BARE HUMØR",
    t=["Maler for humør, søvn, drømmer, energi, mens, smerte, trening, alkohol, meditasjon, lesing, vann, skjermtid, takknemlighet og mer",
       "Eller lag ditt eget kart med ditt eget spørsmål, egne farger og nivåer"],
    h_s="SE HVA SOM HØRER SAMMEN",
    s=["Pixi viser hvilke farger som dukker opp sammen, som uthvilte netter og strålende dager",
       "Måneden din sammenlignet med forrige, og hva som skiller seg ut på hvilken ukedag"],
    h_p="ÅRET DITT SOM PLAKAT",
    p=["Hvert kart som et rundt årshjul, til å dele eller henge på veggen"],
    h_priv="PRIVAT FRA START",
    priv=["Ingen konto, ingen reklame. Dataene dine blir på enheten din"],
    h_prem="PIXI PREMIUM",
    prem1="Pixi er gratis med opptil 4 kart. Pixi Premium låser opp ubegrenset med kart og all statistikk: prøv månedsabonnementet gratis i 3 dager, eller betal én gang for livsvarig tilgang.",
    prem2="Månedsabonnementet fornyes automatisk med mindre det sies opp minst 24 timer før slutten av gjeldende periode. Betalingen belastes Apple-kontoen din. Du kan administrere eller si opp abonnementet i innstillingene for App Store-kontoen din.",
    terms="Bruksvilkår",
    privacy="Personvernerklæring",
    contact="Spørsmål eller ideer? Caspar, utvikleren, leser alle meldinger:",
)

FI = dict(
    name="Pixi: Vuoteni pikseleinä",
    subtitle="Mielialapäiväkirja & seuranta",
    keywords="tunteet,päiväkirja,tavat,kalenteri,kissa,söpö,uni,kuukautiset,unet,värit,hyvinvointi",
    promo="Yksi kysymys joka aamu, yksi väri päivässä. Katso, kuinka vuotesi muuttuu hehkuvaksi kuvaksi Pixin kanssa, pienen kissan, joka kysyy, millainen eilinen oli.",
    intro="Koko vuotesi yhdessä kuvassa. Yksi kysymys joka aamu, yksi väri päivässä. Muutaman viikon päästä näet, mikä todella muovaa päiviäsi.",
    about="Pixi on \"Year in Pixels\" tyylinen mielialan seuranta, jossa pieni piirretty kissa kysyy, millainen eilinen oli. Napauta väriä, valmis. Jokaisesta päivästä tulee pikseli ja jokaisesta vuodesta hehkuva kuva, jota katsot mielelläsi.",
    h_q="YKSI KYSYMYS, 15 SEKUNTIA",
    q=["Lempeä muistutus joka aamu", "Napauta väriä. Ei kirjoittamista, ei paineita", "Jäikö päivä väliin? Täytä se myöhemmin"],
    h_t="PALJON MUUTAKIN KUIN MIELIALA",
    t=["Mallipohjat mielialalle, unelle, unille, energialle, kuukautisille, kivulle, treenille, alkoholille, meditaatiolle, lukemiselle, vedelle, ruutuajalle, kiitollisuudelle ja muulle",
       "Tai luo oma karttasi omalla kysymyksellä, väreillä ja tasoilla"],
    h_s="NÄE, MIKÄ KUULUU YHTEEN",
    s=["Pixi näyttää, mitkä värit esiintyvät yhdessä, kuten levolliset yöt ja säteilevät päivät",
       "Kuukautesi verrattuna edelliseen ja mikä erottuu minäkin viikonpäivänä"],
    h_p="VUOTESI JULISTEENA",
    p=["Jokainen kartta pyöreänä vuosikiekkona, jaettavaksi tai seinälle"],
    h_priv="YKSITYINEN ALUSTA ALKAEN",
    priv=["Ei tiliä, ei mainoksia. Tietosi pysyvät laitteellasi"],
    h_prem="PIXI PREMIUM",
    prem1="Pixi on ilmainen enintään 4 kartalla. Pixi Premium avaa rajattomat kartat ja kaikki tilastot: kokeile kuukausitilausta 3 päivää ilmaiseksi tai maksa kerran ja saat käyttöoikeuden pysyvästi.",
    prem2="Kuukausitilaus uusiutuu automaattisesti, ellei sitä peruta vähintään 24 tuntia ennen nykyisen jakson päättymistä. Maksu veloitetaan Apple-tililtäsi. Voit hallita tai perua tilauksen App Store tilisi asetuksissa.",
    terms="Käyttöehdot",
    privacy="Tietosuojakäytäntö",
    contact="Kysyttävää tai ideoita? Kehittäjä Caspar lukee jokaisen viestin:",
)

PL = dict(
    name="Pixi: Mój rok w pikselach",
    subtitle="Dziennik nastroju i emocji",
    keywords="uczucia,pamiętnik,nawyki,kalendarz,kot,słodki,sen,okres,sny,kolory,samopoczucie",
    promo="Jedno pytanie każdego ranka, jeden kolor każdego dnia. Zobacz, jak Twój rok zmienia się w świecący obraz z Pixi, małym kotem, który pyta, jak minął wczorajszy dzień.",
    intro="Cały Twój rok na jednym obrazie. Jedno pytanie każdego ranka, jeden kolor każdego dnia. Po kilku tygodniach widzisz, co naprawdę kształtuje Twoje dni.",
    about="Pixi to tracker nastroju w stylu \"Year in Pixels\" z małym rysowanym kotem, który pyta, jak minął wczorajszy dzień. Dotknij koloru i gotowe. Każdy dzień staje się pikselem, każdy rok świecącym obrazem, na który lubisz patrzeć.",
    h_q="JEDNO PYTANIE, 15 SEKUND",
    q=["Delikatne przypomnienie każdego ranka", "Dotknij koloru. Bez pisania, bez presji", "Pominięty dzień? Uzupełnij go później"],
    h_t="WIĘCEJ NIŻ NASTRÓJ",
    t=["Szablony dla nastroju, snu, marzeń sennych, energii, okresu, bólu, treningu, alkoholu, medytacji, czytania, wody, czasu przed ekranem, wdzięczności i nie tylko",
       "Albo stwórz własną mapę z własnym pytaniem, kolorami i poziomami"],
    h_s="ZOBACZ, CO IDZIE W PARZE",
    s=["Pixi pokazuje, które kolory pojawiają się razem, na przykład spokojne noce i promienne dni",
       "Twój miesiąc w porównaniu z poprzednim i to, co wyróżnia się w danym dniu tygodnia"],
    h_p="TWÓJ ROK JAKO PLAKAT",
    p=["Każda mapa jako okrągłe koło roku, do udostępnienia lub powieszenia na ścianie"],
    h_priv="PRYWATNOŚĆ OD POCZĄTKU",
    priv=["Bez konta i bez reklam. Twoje dane zostają na Twoim urządzeniu"],
    h_prem="PIXI PREMIUM",
    prem1="Pixi jest darmowe dla maksymalnie 4 map. Pixi Premium odblokowuje nieograniczoną liczbę map i wszystkie statystyki: wypróbuj plan miesięczny przez 3 dni za darmo lub zapłać raz za dostęp na zawsze.",
    prem2="Subskrypcja miesięczna odnawia się automatycznie, chyba że zostanie anulowana co najmniej 24 godziny przed końcem bieżącego okresu. Płatność jest pobierana z Twojego konta Apple. Możesz nią zarządzać lub ją anulować w ustawieniach konta App Store.",
    terms="Warunki korzystania",
    privacy="Polityka prywatności",
    contact="Pytania lub pomysły? Caspar, twórca aplikacji, czyta każdą wiadomość:",
)

CS = dict(
    name="Pixi: Můj rok v pixelech",
    subtitle="Deník nálad a emocí",
    keywords="pocity,návyky,kalendář,kočka,roztomilé,spánek,menstruace,sny,barvy,pohoda,tracker",
    promo="Jedna otázka každé ráno, jedna barva každý den. Sleduj, jak se tvůj rok mění v zářivý obraz s Pixi, malou kočkou, která se ptá, jaký byl včerejšek.",
    intro="Celý tvůj rok v jednom obrázku. Jedna otázka každé ráno, jedna barva každý den. Po pár týdnech uvidíš, co tvé dny opravdu ovlivňuje.",
    about="Pixi je sledování nálad ve stylu \"Year in Pixels\" s malou kreslenou kočkou, která se ptá, jaký byl včerejšek. Klepni na barvu a hotovo. Z každého dne je pixel, z každého roku zářivý obrázek, na který se rád díváš.",
    h_q="JEDNA OTÁZKA, 15 SEKUND",
    q=["Jemná připomínka každé ráno", "Klepni na barvu. Žádné psaní, žádný tlak", "Vynechal jsi den? Doplň ho později"],
    h_t="VÍC NEŽ JEN NÁLADA",
    t=["Šablony pro náladu, spánek, sny, energii, menstruaci, bolest, trénink, alkohol, meditaci, čtení, vodu, čas u obrazovky, vděčnost a další",
       "Nebo si vytvoř vlastní mapu s vlastní otázkou, barvami a úrovněmi"],
    h_s="PODÍVEJ SE, CO K SOBĚ PATŘÍ",
    s=["Pixi ukazuje, které barvy se objevují spolu, třeba klidné noci a zářivé dny",
       "Tvůj měsíc ve srovnání s předchozím a co vyčnívá v jednotlivých dnech týdne"],
    h_p="TVŮJ ROK JAKO PLAKÁT",
    p=["Každá mapa jako kulaté kolo roku, ke sdílení nebo na zeď"],
    h_priv="SOUKROMÍ OD ZAČÁTKU",
    priv=["Žádný účet, žádné reklamy. Tvá data zůstávají ve tvém zařízení"],
    h_prem="PIXI PREMIUM",
    prem1="Pixi je zdarma až pro 4 mapy. Pixi Premium odemyká neomezený počet map a všechny statistiky: vyzkoušej měsíční předplatné 3 dny zdarma, nebo zaplať jednou a měj přístup navždy.",
    prem2="Měsíční předplatné se automaticky obnovuje, pokud není zrušeno alespoň 24 hodin před koncem aktuálního období. Platba se strhává z tvého účtu Apple. Spravovat nebo zrušit ho můžeš v nastavení svého účtu App Store.",
    terms="Podmínky použití",
    privacy="Zásady ochrany osobních údajů",
    contact="Otázky nebo nápady? Caspar, vývojář, čte každou zprávu:",
)

SK = dict(
    name="Pixi: Môj rok v pixeloch",
    subtitle="Denník nálad a emócií",
    keywords="pocity,návyky,kalendár,mačka,roztomilé,spánok,menštruácia,sny,farby,pohoda,tracker",
    promo="Jedna otázka každé ráno, jedna farba každý deň. Sleduj, ako sa tvoj rok mení na žiarivý obraz s Pixi, malou mačkou, ktorá sa pýta, aký bol včerajšok.",
    intro="Celý tvoj rok na jednom obrázku. Jedna otázka každé ráno, jedna farba každý deň. Po pár týždňoch uvidíš, čo tvoje dni naozaj ovplyvňuje.",
    about="Pixi je sledovanie nálad v štýle \"Year in Pixels\" s malou kreslenou mačkou, ktorá sa pýta, aký bol včerajšok. Ťukni na farbu a hotovo. Z každého dňa je pixel, z každého roka žiarivý obrázok, na ktorý sa rád pozeráš.",
    h_q="JEDNA OTÁZKA, 15 SEKÚND",
    q=["Jemná pripomienka každé ráno", "Ťukni na farbu. Žiadne písanie, žiadny tlak", "Vynechal si deň? Doplň ho neskôr"],
    h_t="VIAC NEŽ LEN NÁLADA",
    t=["Šablóny pre náladu, spánok, sny, energiu, menštruáciu, bolesť, tréning, alkohol, meditáciu, čítanie, vodu, čas pri obrazovke, vďačnosť a ďalšie",
       "Alebo si vytvor vlastnú mapu s vlastnou otázkou, farbami a úrovňami"],
    h_s="POZRI SA, ČO K SEBE PATRÍ",
    s=["Pixi ukazuje, ktoré farby sa objavujú spolu, napríklad pokojné noci a žiarivé dni",
       "Tvoj mesiac v porovnaní s predchádzajúcim a čo vyniká v jednotlivých dňoch týždňa"],
    h_p="TVOJ ROK AKO PLAGÁT",
    p=["Každá mapa ako okrúhle koleso roka, na zdieľanie alebo na stenu"],
    h_priv="SÚKROMIE OD ZAČIATKU",
    priv=["Žiadny účet, žiadne reklamy. Tvoje dáta zostávajú v tvojom zariadení"],
    h_prem="PIXI PREMIUM",
    prem1="Pixi je zadarmo až pre 4 mapy. Pixi Premium odomyká neobmedzený počet máp a všetky štatistiky: vyskúšaj mesačné predplatné 3 dni zadarmo alebo zaplať raz a maj prístup navždy.",
    prem2="Mesačné predplatné sa automaticky obnovuje, ak ho nezrušíš aspoň 24 hodín pred koncom aktuálneho obdobia. Platba sa strhne z tvojho účtu Apple. Spravovať alebo zrušiť ho môžeš v nastaveniach svojho účtu App Store.",
    terms="Podmienky používania",
    privacy="Zásady ochrany súkromia",
    contact="Otázky alebo nápady? Caspar, vývojár, číta každú správu:",
)

HU = dict(
    name="Pixi: Az évem pixelekben",
    subtitle="Hangulatnapló és követő",
    keywords="érzelmek,érzések,szokások,naptár,macska,cuki,alvás,menstruáció,álmok,színek,jóllét",
    promo="Minden reggel egy kérdés, minden nap egy szín. Nézd, ahogy az éved ragyogó képpé válik Pixivel, a kis cicával, aki megkérdezi, milyen volt a tegnap.",
    intro="Az egész éved egyetlen képen. Minden reggel egy kérdés, minden nap egy szín. Néhány hét után látod, mi formálja igazán a napjaidat.",
    about="A Pixi egy \"Year in Pixels\" stílusú hangulatkövető, amelyben egy kis rajzolt cica megkérdezi, milyen volt a tegnap. Koppints egy színre, és kész. Minden napból egy pixel lesz, minden évből egy ragyogó kép, amit szívesen nézel.",
    h_q="EGY KÉRDÉS, 15 MÁSODPERC",
    q=["Kedves emlékeztető minden reggel", "Koppints egy színre. Nincs gépelés, nincs nyomás", "Kimaradt egy nap? Pótold később"],
    h_t="TÖBB MINT HANGULAT",
    t=["Sablonok hangulathoz, alváshoz, álmokhoz, energiához, menstruációhoz, fájdalomhoz, edzéshez, alkoholhoz, meditációhoz, olvasáshoz, vízhez, képernyőidőhöz, hálához és még sok máshoz",
       "Vagy hozd létre a saját térképedet saját kérdéssel, színekkel és szintekkel"],
    h_s="LÁSD, MI TARTOZIK ÖSSZE",
    s=["A Pixi megmutatja, mely színek jelennek meg együtt, például a pihentető éjszakák és a ragyogó napok",
       "A hónapod az előzőhöz képest, és hogy melyik napon mi tűnik ki"],
    h_p="AZ ÉVED POSZTERKÉNT",
    p=["Minden térkép kerek évkerékként, megosztásra vagy a falra"],
    h_priv="ADATVÉDELEM AZ ELEJÉTŐL",
    priv=["Nincs fiók, nincs reklám. Az adataid a készülékeden maradnak"],
    h_prem="PIXI PREMIUM",
    prem1="A Pixi legfeljebb 4 térképig ingyenes. A Pixi Premium korlátlan térképet és minden statisztikát felold: próbáld ki a havi csomagot 3 napig ingyen, vagy fizess egyszer az örökös hozzáférésért.",
    prem2="A havi előfizetés automatikusan megújul, hacsak nem mondod le legalább 24 órával az aktuális időszak vége előtt. A díjat az Apple-fiókod terheli. Az előfizetést az App Store-fiókod beállításaiban kezelheted vagy mondhatod le.",
    terms="Felhasználási feltételek",
    privacy="Adatvédelmi irányelvek",
    contact="Kérdésed vagy ötleted van? Caspar, a fejlesztő, minden üzenetet elolvas:",
)

RO = dict(
    name="Pixi: Anul meu în pixeli",
    subtitle="Jurnal de stare și emoții",
    keywords="dispoziție,sentimente,obiceiuri,calendar,pisică,drăguț,somn,ciclu,vise,culori,bunăstare",
    promo="O întrebare în fiecare dimineață, o culoare pe zi. Privește cum anul tău devine o imagine luminoasă cu Pixi, pisicuța care te întreabă cum a fost ieri.",
    intro="Tot anul tău într-o singură imagine. O întrebare în fiecare dimineață, o culoare pe zi. După câteva săptămâni vezi ce îți marchează cu adevărat zilele.",
    about="Pixi este un tracker de dispoziție în stilul \"Year in Pixels\", cu o pisicuță desenată care te întreabă cum a fost ieri. Atinge o culoare și gata. Fiecare zi devine un pixel, fiecare an o imagine luminoasă pe care îți place să o privești.",
    h_q="O ÎNTREBARE, 15 SECUNDE",
    q=["Un memento blând în fiecare dimineață", "Atinge o culoare. Fără scris, fără presiune", "Ai ratat o zi? Complet-o mai târziu"],
    h_t="MAI MULT DECÂT DISPOZIȚIA",
    t=["Șabloane pentru dispoziție, somn, vise, energie, ciclu, durere, antrenament, alcool, meditație, lectură, apă, timp petrecut pe ecran, recunoștință și altele",
       "Sau creează propria hartă, cu propria întrebare, culori și niveluri"],
    h_s="VEZI CE MERGE ÎMPREUNĂ",
    s=["Pixi îți arată ce culori apar împreună, precum nopțile odihnitoare și zilele radioase",
       "Luna ta comparată cu cea anterioară și ce iese în evidență în fiecare zi a săptămânii"],
    h_p="ANUL TĂU CA POSTER",
    p=["Fiecare hartă ca o roată a anului, de distribuit sau de pus pe perete"],
    h_priv="PRIVAT DE LA ÎNCEPUT",
    priv=["Fără cont, fără reclame. Datele tale rămân pe dispozitivul tău"],
    h_prem="PIXI PREMIUM",
    prem1="Pixi este gratuit pentru până la 4 hărți. Pixi Premium deblochează hărți nelimitate și toate statisticile: încearcă abonamentul lunar gratuit timp de 3 zile sau plătește o singură dată pentru acces pe viață.",
    prem2="Abonamentul lunar se reînnoiește automat, cu excepția cazului în care este anulat cu cel puțin 24 de ore înainte de sfârșitul perioadei curente. Plata se face din contul tău Apple. Îl poți gestiona sau anula din setările contului tău App Store.",
    terms="Termeni de utilizare",
    privacy="Politica de confidențialitate",
    contact="Întrebări sau idei? Caspar, dezvoltatorul, citește fiecare mesaj:",
)

HR = dict(
    name="Pixi: Moja godina u pikselima",
    subtitle="Dnevnik raspoloženja",
    keywords="emocije,osjećaji,navike,kalendar,mačka,slatko,san,menstruacija,snovi,boje,tracker",
    promo="Jedno pitanje svako jutro, jedna boja svaki dan. Gledaj kako tvoja godina postaje blistava slika uz Pixi, malu mačku koja pita kakav je bio jučerašnji dan.",
    intro="Cijela tvoja godina na jednoj slici. Jedno pitanje svako jutro, jedna boja svaki dan. Nakon nekoliko tjedana vidiš što zaista oblikuje tvoje dane.",
    about="Pixi je praćenje raspoloženja u stilu \"Year in Pixels\" s malom nacrtanom mačkom koja pita kakav je bio jučerašnji dan. Dodirni boju i gotovo. Svaki dan postaje piksel, svaka godina blistava slika koju rado gledaš.",
    h_q="JEDNO PITANJE, 15 SEKUNDI",
    q=["Nježan podsjetnik svako jutro", "Dodirni boju. Bez pisanja, bez pritiska", "Propustio si dan? Popuni ga kasnije"],
    h_t="VIŠE OD RASPOLOŽENJA",
    t=["Predlošci za raspoloženje, san, snove, energiju, menstruaciju, bol, trening, alkohol, meditaciju, čitanje, vodu, vrijeme pred ekranom, zahvalnost i još mnogo toga",
       "Ili izradi vlastitu kartu s vlastitim pitanjem, bojama i razinama"],
    h_s="POGLEDAJ ŠTO IDE ZAJEDNO",
    s=["Pixi pokazuje koje se boje pojavljuju zajedno, poput odmornih noći i blistavih dana",
       "Tvoj mjesec u usporedbi s prethodnim i što se ističe kojeg dana u tjednu"],
    h_p="TVOJA GODINA KAO POSTER",
    p=["Svaka karta kao okrugli kotač godine, za dijeljenje ili za zid"],
    h_priv="PRIVATNO OD POČETKA",
    priv=["Bez računa, bez oglasa. Tvoji podaci ostaju na tvom uređaju"],
    h_prem="PIXI PREMIUM",
    prem1="Pixi je besplatan za do 4 karte. Pixi Premium otključava neograničen broj karata i svu statistiku: isprobaj mjesečni plan besplatno 3 dana ili plati jednom za doživotni pristup.",
    prem2="Mjesečna pretplata automatski se obnavlja ako se ne otkaže najmanje 24 sata prije kraja trenutnog razdoblja. Plaćanje se naplaćuje s tvog Apple računa. Pretplatom možeš upravljati ili je otkazati u postavkama svog App Store računa.",
    terms="Uvjeti korištenja",
    privacy="Pravila privatnosti",
    contact="Pitanja ili ideje? Caspar, razvojni programer, čita svaku poruku:",
)

EL = dict(
    name="Pixi: Η χρονιά μου σε pixel",
    subtitle="Ημερολόγιο διάθεσης",
    keywords="συναισθήματα,συνήθειες,γάτα,ύπνος,περίοδος,όνειρα,χρώματα,ευεξία",
    promo="Μία ερώτηση κάθε πρωί, ένα χρώμα κάθε μέρα. Δες τη χρονιά σου να γίνεται μια φωτεινή εικόνα με το Pixi, το γατάκι που ρωτά πώς ήταν η χθεσινή μέρα.",
    intro="Όλη η χρονιά σου σε μία εικόνα. Μία ερώτηση κάθε πρωί, ένα χρώμα κάθε μέρα. Μετά από λίγες εβδομάδες βλέπεις τι διαμορφώνει πραγματικά τις μέρες σου.",
    about="Το Pixi είναι ένα ημερολόγιο διάθεσης σε στιλ \"Year in Pixels\" με ένα μικρό ζωγραφιστό γατάκι που ρωτά πώς ήταν η χθεσινή μέρα. Πάτησε ένα χρώμα και τελείωσες. Κάθε μέρα γίνεται ένα pixel και κάθε χρονιά μια φωτεινή εικόνα που σου αρέσει να κοιτάς.",
    h_q="ΜΙΑ ΕΡΩΤΗΣΗ, 15 ΔΕΥΤΕΡΟΛΕΠΤΑ",
    q=["Μια απαλή υπενθύμιση κάθε πρωί", "Πάτησε ένα χρώμα. Χωρίς πληκτρολόγηση, χωρίς πίεση", "Έχασες μια μέρα; Συμπλήρωσέ τη αργότερα"],
    h_t="ΠΟΛΛΑ ΠΕΡΙΣΣΟΤΕΡΑ ΑΠΟ ΔΙΑΘΕΣΗ",
    t=["Πρότυπα για διάθεση, ύπνο, όνειρα, ενέργεια, περίοδο, πόνο, προπόνηση, αλκοόλ, διαλογισμό, διάβασμα, νερό, χρόνο οθόνης, ευγνωμοσύνη και άλλα",
       "Ή φτιάξε τον δικό σου χάρτη με τη δική σου ερώτηση, χρώματα και επίπεδα"],
    h_s="ΔΕΣ ΤΙ ΠΑΕΙ ΜΑΖΙ",
    s=["Το Pixi δείχνει ποια χρώματα εμφανίζονται μαζί, όπως ξεκούραστες νύχτες και λαμπερές μέρες",
       "Ο μήνας σου σε σύγκριση με τον προηγούμενο και τι ξεχωρίζει κάθε μέρα της εβδομάδας"],
    h_p="Η ΧΡΟΝΙΑ ΣΟΥ ΩΣ ΑΦΙΣΑ",
    p=["Κάθε χάρτης ως στρογγυλός τροχός της χρονιάς, για κοινοποίηση ή για τον τοίχο"],
    h_priv="ΙΔΙΩΤΙΚΟ ΑΠΟ ΤΗΝ ΑΡΧΗ",
    priv=["Χωρίς λογαριασμό, χωρίς διαφημίσεις. Τα δεδομένα σου μένουν στη συσκευή σου"],
    h_prem="PIXI PREMIUM",
    prem1="Το Pixi είναι δωρεάν για έως 4 χάρτες. Το Pixi Premium ξεκλειδώνει απεριόριστους χάρτες και όλα τα στατιστικά: δοκίμασε το μηνιαίο πρόγραμμα δωρεάν για 3 ημέρες ή πλήρωσε μία φορά για πρόσβαση για πάντα.",
    prem2="Η μηνιαία συνδρομή ανανεώνεται αυτόματα, εκτός αν ακυρωθεί τουλάχιστον 24 ώρες πριν από το τέλος της τρέχουσας περιόδου. Η χρέωση γίνεται στον λογαριασμό σου Apple. Μπορείς να τη διαχειριστείς ή να την ακυρώσεις στις ρυθμίσεις του λογαριασμού σου στο App Store.",
    terms="Όροι χρήσης",
    privacy="Πολιτική απορρήτου",
    contact="Ερωτήσεις ή ιδέες; Ο Caspar, ο δημιουργός, διαβάζει κάθε μήνυμα:",
)

TR = dict(
    name="Pixi: Piksellerle Yılım",
    subtitle="Ruh Hali Günlüğü ve Takip",
    keywords="duygular,hisler,alışkanlık,takvim,kedi,sevimli,uyku,regl,rüya,renkler,öz bakım",
    promo="Her sabah bir soru, her gün bir renk. Dünün nasıl geçtiğini soran küçük kedi Pixi ile yılının parlak bir resme dönüşmesini izle.",
    intro="Tüm yılın tek bir resimde. Her sabah bir soru, her gün bir renk. Birkaç hafta sonra günlerini gerçekten neyin şekillendirdiğini görürsün.",
    about="Pixi, dünün nasıl geçtiğini soran küçük çizim bir kediyle \"Year in Pixels\" tarzında bir ruh hali takipçisidir. Bir renge dokun, bitti. Her gün bir piksel, her yıl bakmaktan keyif aldığın parlak bir resim olur.",
    h_q="TEK SORU, 15 SANİYE",
    q=["Her sabah nazik bir hatırlatma", "Bir renge dokun. Yazmak yok, baskı yok", "Bir günü mü kaçırdın? Sonra doldur"],
    h_t="RUH HALİNDEN FAZLASI",
    t=["Ruh hali, uyku, rüyalar, enerji, regl, ağrı, antrenman, alkol, meditasyon, okuma, su, ekran süresi, şükran ve daha fazlası için şablonlar",
       "Ya da kendi sorun, renklerin ve seviyelerinle kendi haritanı oluştur"],
    h_s="NEYİN BİRLİKTE GİTTİĞİNİ GÖR",
    s=["Pixi hangi renklerin birlikte göründüğünü gösterir, örneğin dinlendirici geceler ve parlak günler",
       "Ayının bir önceki ayla karşılaştırması ve haftanın hangi gününde neyin öne çıktığı"],
    h_p="POSTER OLARAK YILIN",
    p=["Her harita yuvarlak bir yıl çarkı olarak, paylaşmak ya da duvara asmak için"],
    h_priv="BAŞTAN SONA GİZLİ",
    priv=["Hesap yok, reklam yok. Verilerin cihazında kalır"],
    h_prem="PIXI PREMIUM",
    prem1="Pixi en fazla 4 harita ile ücretsizdir. Pixi Premium sınırsız harita ve tüm istatistikleri açar: aylık planı 3 gün ücretsiz dene ya da ömür boyu erişim için bir kez öde.",
    prem2="Aylık abonelik, mevcut dönemin bitiminden en az 24 saat önce iptal edilmediği sürece otomatik olarak yenilenir. Ödeme Apple hesabından alınır. Aboneliğini App Store hesap ayarlarından yönetebilir veya iptal edebilirsin.",
    terms="Kullanım Koşulları",
    privacy="Gizlilik Politikası",
    contact="Soruların veya fikirlerin mi var? Geliştirici Caspar her mesajı okur:",
)

RU = dict(
    name="Pixi: Мой год в пикселях",
    subtitle="Дневник настроения и эмоций",
    keywords="чувства,привычки,календарь,кот,милый,сон,цикл,сны,цвета,трекер",
    promo="Один вопрос каждое утро, один цвет каждый день. Смотри, как твой год превращается в яркую картину вместе с Pixi, котиком, который спрашивает, как прошёл вчерашний день.",
    intro="Весь твой год на одной картинке. Один вопрос каждое утро, один цвет каждый день. Через несколько недель ты увидишь, что на самом деле определяет твои дни.",
    about="Pixi помогает отслеживать настроение в стиле «Year in Pixels»: маленький нарисованный котик спрашивает, как прошёл вчерашний день. Коснись цвета, и готово. Каждый день становится пикселем, каждый год яркой картиной, на которую приятно смотреть.",
    h_q="ОДИН ВОПРОС, 15 СЕКУНД",
    q=["Мягкое напоминание каждое утро", "Коснись цвета. Ничего не нужно писать, никакого давления", "Пропустил день? Заполни его позже"],
    h_t="НЕ ТОЛЬКО НАСТРОЕНИЕ",
    t=["Шаблоны для настроения, сна, сновидений, энергии, цикла, боли, тренировок, алкоголя, медитации, чтения, воды, экранного времени, благодарности и многого другого",
       "Или создай свою карту со своим вопросом, цветами и уровнями"],
    h_s="СМОТРИ, ЧТО СВЯЗАНО",
    s=["Pixi показывает, какие цвета появляются вместе, например спокойные ночи и яркие дни",
       "Твой месяц в сравнении с предыдущим и то, что выделяется в разные дни недели"],
    h_p="ТВОЙ ГОД КАК ПОСТЕР",
    p=["Каждая карта в виде круглого колеса года, чтобы поделиться или повесить на стену"],
    h_priv="ПРИВАТНОСТЬ С САМОГО НАЧАЛА",
    priv=["Без аккаунта и без рекламы. Твои данные остаются на твоём устройстве"],
    h_prem="PIXI PREMIUM",
    prem1="Pixi бесплатен для 4 карт. Pixi Premium открывает неограниченное число карт и всю статистику: попробуй месячный план бесплатно 3 дня или заплати один раз за доступ навсегда.",
    prem2="Месячная подписка продлевается автоматически, если её не отменить как минимум за 24 часа до окончания текущего периода. Оплата списывается с твоего аккаунта Apple. Управлять подпиской или отменить её можно в настройках аккаунта App Store.",
    terms="Условия использования",
    privacy="Политика конфиденциальности",
    contact="Вопросы или идеи? Каспар, разработчик, читает каждое сообщение:",
)

UK = dict(
    name="Pixi: Мій рік у пікселях",
    subtitle="Щоденник настрою та емоцій",
    keywords="почуття,звички,календар,кіт,милий,сон,цикл,сновидіння,кольори",
    promo="Одне питання щоранку, один колір щодня. Дивись, як твій рік перетворюється на яскраву картину разом із Pixi, котиком, який питає, як минув учорашній день.",
    intro="Увесь твій рік на одній картинці. Одне питання щоранку, один колір щодня. За кілька тижнів ти побачиш, що насправді визначає твої дні.",
    about="Pixi допомагає відстежувати настрій у стилі «Year in Pixels»: маленький намальований котик питає, як минув учорашній день. Торкнися кольору, і готово. Кожен день стає пікселем, кожен рік яскравою картиною, на яку приємно дивитися.",
    h_q="ОДНЕ ПИТАННЯ, 15 СЕКУНД",
    q=["М'яке нагадування щоранку", "Торкнися кольору. Нічого не треба писати, жодного тиску", "Пропустив день? Заповни його пізніше"],
    h_t="НЕ ЛИШЕ НАСТРІЙ",
    t=["Шаблони для настрою, сну, сновидінь, енергії, циклу, болю, тренувань, алкоголю, медитації, читання, води, екранного часу, вдячності та іншого",
       "Або створи власну карту зі своїм питанням, кольорами та рівнями"],
    h_s="ДИВИСЬ, ЩО ПОВ'ЯЗАНЕ",
    s=["Pixi показує, які кольори з'являються разом, наприклад спокійні ночі та яскраві дні",
       "Твій місяць порівняно з попереднім і те, що вирізняється в різні дні тижня"],
    h_p="ТВІЙ РІК ЯК ПОСТЕР",
    p=["Кожна карта у вигляді круглого колеса року, щоб поділитися або повісити на стіну"],
    h_priv="ПРИВАТНІСТЬ ВІД САМОГО ПОЧАТКУ",
    priv=["Без акаунта і без реклами. Твої дані залишаються на твоєму пристрої"],
    h_prem="PIXI PREMIUM",
    prem1="Pixi безкоштовний для 4 карт. Pixi Premium відкриває необмежену кількість карт і всю статистику: спробуй місячний план безкоштовно 3 дні або заплати один раз за доступ назавжди.",
    prem2="Місячна підписка поновлюється автоматично, якщо її не скасувати щонайменше за 24 години до кінця поточного періоду. Оплата списується з твого облікового запису Apple. Керувати підпискою або скасувати її можна в налаштуваннях облікового запису App Store.",
    terms="Умови використання",
    privacy="Політика конфіденційності",
    contact="Питання чи ідеї? Каспар, розробник, читає кожне повідомлення:",
)

GROUP_B = {
    "sv": SV, "da": DA, "no": NO, "fi": FI, "pl": PL, "cs": CS, "sk": SK,
    "hu": HU, "ro": RO, "hr": HR, "el": EL, "tr": TR, "ru": RU, "uk": UK,
}
