# Store texts, group A: English, German, Romance languages, Dutch.
# No dashes as punctuation anywhere (house rule).

EN_US = dict(
    name="Pixi: My Year in Pixels",
    subtitle="Mood Tracker & Daily Journal",
    keywords="emotion,feelings,diary,habit,calendar,cat,cute,aesthetic,sleep,period,dream,color,chart,self,care",
    promo="One question every morning, one color per day. Watch your year turn into a glowing picture with Pixi, the little cat who asks how yesterday was.",
    intro="Your whole year in one picture. One question every morning, one color per day. After a few weeks you see what really shapes your days.",
    about="Pixi is a Year in Pixels mood tracker with a little sketched cat who asks how yesterday was. Tap a color, done. Every day becomes a pixel, every year a glowing picture you love to look at.",
    h_q="ONE QUESTION, 15 SECONDS",
    q=["A gentle reminder every morning", "Tap a color. No typing, no pressure", "Missed a day? Fill it in later"],
    h_t="TRACK MORE THAN MOOD",
    t=["Templates for mood, sleep, dreams, energy, period, pain, training, alcohol, meditation, reading, water, screen time, gratitude and more",
       "Or create your own map with your own question, colors and levels"],
    h_s="SEE WHAT BELONGS TOGETHER",
    s=["Pixi shows which colors show up together, like restful nights and radiant days",
       "Your month compared with the last one, and what stands out on which weekday"],
    h_p="YOUR YEAR AS A POSTER",
    p=["Every map as a round year wheel, to share or to hang on the wall"],
    h_priv="PRIVATE BY DESIGN",
    priv=["No account, no ads. Your entries stay on your device"],
    h_prem="PIXI PREMIUM",
    prem1="Pixi is free with up to 4 maps. Pixi Premium unlocks unlimited maps and all statistics: try the monthly plan free for 3 days, or pay once for lifetime access.",
    prem2="The monthly subscription renews automatically unless it is canceled at least 24 hours before the end of the current period. Payment is charged to your Apple Account. You can manage or cancel it in your App Store account settings.",
    terms="Terms of Use",
    privacy="Privacy Policy",
    contact="Questions or ideas? Caspar, the developer, reads every message:",
)

def _british(d):
    out = {}
    for k, v in d.items():
        if isinstance(v, list):
            out[k] = [x.replace("colors", "colours").replace("color", "colour").replace("canceled", "cancelled") for x in v]
        elif k in ("name",):
            out[k] = v
        else:
            out[k] = v.replace("colors", "colours").replace("color", "colour").replace("canceled", "cancelled")
    out["keywords"] = "emotion,feelings,diary,habit,calendar,cat,cute,aesthetic,sleep,period,dream,colour,chart,self,care"
    return out

EN_GB = _british(EN_US)

DE = dict(
    name="Pixi: Mein Jahr in Pixeln",
    subtitle="Stimmungstagebuch & Tracker",
    keywords="gefühle,gefühlstagebuch,tagebuch,journal,mood,habit,kalender,katze,schlaf,zyklus,traum,farben",
    promo="Jeden Morgen eine Frage, jeden Tag eine Farbe. Sieh zu, wie dein Jahr zu einem leuchtenden Bild wird, mit Pixi, der kleinen Katze, die fragt, wie gestern war.",
    intro="Dein ganzes Jahr in einem Bild. Jeden Morgen eine Frage, jeden Tag eine Farbe. Nach ein paar Wochen siehst du, was deine Tage wirklich prägt.",
    about="Pixi ist ein Stimmungstracker im Stil „Year in Pixels“ mit einer kleinen gezeichneten Katze, die dich fragt, wie gestern war. Farbe antippen, fertig. Jeder Tag wird ein Pixel, jedes Jahr ein leuchtendes Bild, das du gerne anschaust.",
    h_q="EINE FRAGE, 15 SEKUNDEN",
    q=["Jeden Morgen eine sanfte Erinnerung", "Farbe antippen. Kein Schreiben, kein Druck", "Einen Tag verpasst? Einfach später nachtragen"],
    h_t="MEHR ALS NUR STIMMUNG",
    t=["Vorlagen für Stimmung, Schlaf, Träume, Energie, Periode, Schmerzen, Training, Alkohol, Meditation, Lesen, Wasser, Bildschirmzeit, Dankbarkeit und mehr",
       "Oder deine eigene Map mit eigener Frage, eigenen Farben und Stufen"],
    h_s="SIEH, WAS ZUSAMMENGEHÖRT",
    s=["Pixi zeigt, welche Farben zusammen auftauchen, zum Beispiel erholsame Nächte und strahlende Tage",
       "Dein Monat im Vergleich zum letzten und was an welchem Wochentag auffällt"],
    h_p="DEIN JAHR ALS POSTER",
    p=["Jede Map als rundes Jahresrad, zum Teilen oder für die Wand"],
    h_priv="PRIVAT VON ANFANG AN",
    priv=["Kein Konto, keine Werbung. Deine Einträge bleiben auf deinem Gerät"],
    h_prem="PIXI PREMIUM",
    prem1="Pixi ist mit bis zu 4 Maps kostenlos. Pixi Premium schaltet unbegrenzt Maps und alle Statistiken frei: Teste das Monatsabo 3 Tage kostenlos oder zahle einmal und behalte Pixi für immer.",
    prem2="Das Monatsabo verlängert sich automatisch, wenn es nicht mindestens 24 Stunden vor Ende des aktuellen Zeitraums gekündigt wird. Die Zahlung erfolgt über deinen Apple Account. Verwalten und kündigen kannst du es in den Einstellungen deines App Store Accounts.",
    terms="Nutzungsbedingungen",
    privacy="Datenschutz",
    contact="Fragen oder Ideen? Caspar, der Entwickler, liest jede Nachricht:",
)

FR = dict(
    name="Pixi : Mon année en pixels",
    subtitle="Suivi d'humeur et journal",
    keywords="émotions,sentiments,agenda,habitudes,calendrier,chat,mignon,sommeil,règles,rêves,couleurs,bien-être",
    promo="Une question chaque matin, une couleur par jour. Regarde ton année devenir une image lumineuse avec Pixi, le petit chat qui te demande comment s'est passé hier.",
    intro="Toute ton année en une seule image. Une question chaque matin, une couleur par jour. Après quelques semaines, tu vois ce qui façonne vraiment tes journées.",
    about="Pixi est un suivi d'humeur façon « Year in Pixels » avec un petit chat dessiné qui te demande comment s'est passé hier. Touche une couleur, c'est fait. Chaque jour devient un pixel, chaque année une image lumineuse que tu aimes regarder.",
    h_q="UNE QUESTION, 15 SECONDES",
    q=["Un doux rappel chaque matin", "Touche une couleur. Rien à écrire, aucune pression", "Un jour oublié ? Complète-le plus tard"],
    h_t="BIEN PLUS QUE L'HUMEUR",
    t=["Des modèles pour l'humeur, le sommeil, les rêves, l'énergie, les règles, la douleur, le sport, l'alcool, la méditation, la lecture, l'eau, le temps d'écran, la gratitude et plus encore",
       "Ou crée ta propre carte avec ta question, tes couleurs et tes niveaux"],
    h_s="VOIS CE QUI VA ENSEMBLE",
    s=["Pixi montre quelles couleurs apparaissent ensemble, comme des nuits reposantes et des journées radieuses",
       "Ton mois comparé au précédent, et ce qui ressort selon le jour de la semaine"],
    h_p="TON ANNÉE EN POSTER",
    p=["Chaque carte en roue de l'année, à partager ou à accrocher au mur"],
    h_priv="PRIVÉ PAR NATURE",
    priv=["Pas de compte, pas de pub. Tes données restent sur ton appareil"],
    h_prem="PIXI PREMIUM",
    prem1="Pixi est gratuit jusqu'à 4 cartes. Pixi Premium débloque les cartes illimitées et toutes les statistiques : essaie l'abonnement mensuel gratuitement pendant 3 jours ou paie une seule fois pour un accès à vie.",
    prem2="L'abonnement mensuel se renouvelle automatiquement, sauf s'il est résilié au moins 24 heures avant la fin de la période en cours. Le paiement est débité sur ton compte Apple. Tu peux le gérer ou le résilier dans les réglages de ton compte App Store.",
    terms="Conditions d'utilisation",
    privacy="Politique de confidentialité",
    contact="Des questions ou des idées ? Caspar, le développeur, lit chaque message :",
)

ES = dict(
    name="Pixi: Mi año en píxeles",
    subtitle="Diario de ánimo y emociones",
    keywords="humor,sentimientos,hábitos,calendario,gato,bonito,sueño,regla,colores,autocuidado,bienestar,estética",
    promo="Una pregunta cada mañana, un color cada día. Mira cómo tu año se convierte en una imagen luminosa con Pixi, el gatito que te pregunta qué tal fue ayer.",
    intro="Todo tu año en una sola imagen. Una pregunta cada mañana, un color cada día. Tras unas semanas verás qué marca de verdad tus días.",
    about="Pixi es un registro de ánimo al estilo «Year in Pixels» con un gatito dibujado que te pregunta qué tal fue ayer. Toca un color y listo. Cada día se convierte en un píxel y cada año en una imagen luminosa que te encantará mirar.",
    h_q="UNA PREGUNTA, 15 SEGUNDOS",
    q=["Un recordatorio suave cada mañana", "Toca un color. Sin escribir, sin presión", "¿Se te pasó un día? Complétalo después"],
    h_t="MUCHO MÁS QUE EL ÁNIMO",
    t=["Plantillas para ánimo, descanso, sueños, energía, regla, dolor, entrenamiento, alcohol, meditación, lectura, agua, tiempo de pantalla, gratitud y más",
       "O crea tu propio mapa con tu pregunta, tus colores y tus niveles"],
    h_s="DESCUBRE LO QUE VA JUNTO",
    s=["Pixi te muestra qué colores aparecen juntos, como noches reparadoras y días radiantes",
       "Tu mes comparado con el anterior y lo que destaca según el día de la semana"],
    h_p="TU AÑO COMO PÓSTER",
    p=["Cada mapa como una rueda del año, para compartir o colgar en la pared"],
    h_priv="PRIVADO DESDE EL PRINCIPIO",
    priv=["Sin cuenta ni anuncios. Tus datos se quedan en tu dispositivo"],
    h_prem="PIXI PREMIUM",
    prem1="Pixi es gratis con hasta 4 mapas. Pixi Premium desbloquea mapas ilimitados y todas las estadísticas: prueba el plan mensual gratis durante 3 días o paga una sola vez para tenerlo para siempre.",
    prem2="La suscripción mensual se renueva automáticamente salvo que se cancele al menos 24 horas antes del final del periodo actual. El pago se carga en tu cuenta de Apple. Puedes gestionarla o cancelarla en los ajustes de tu cuenta del App Store.",
    terms="Condiciones de uso",
    privacy="Política de privacidad",
    contact="¿Preguntas o ideas? Caspar, el desarrollador, lee todos los mensajes:",
)

ES_MX = dict(ES)
ES_MX.update(
    keywords="humor,sentimientos,hábitos,calendario,gato,bonito,sueño,periodo,colores,autocuidado,bienestar,estética",
    prem2="La suscripción mensual se renueva automáticamente a menos que se cancele al menos 24 horas antes del final del periodo actual. El pago se carga a tu cuenta de Apple. Puedes administrarla o cancelarla en la configuración de tu cuenta del App Store.",
)

IT = dict(
    name="Pixi: Il mio anno in pixel",
    subtitle="Diario dell'umore ed emozioni",
    keywords="sentimenti,abitudini,calendario,gatto,carino,sonno,ciclo,sogni,colori,benessere,estetica,tracker",
    promo="Una domanda ogni mattina, un colore al giorno. Guarda il tuo anno diventare un'immagine luminosa con Pixi, il gattino che ti chiede com'è andato ieri.",
    intro="Tutto il tuo anno in un'unica immagine. Una domanda ogni mattina, un colore al giorno. Dopo qualche settimana capisci cosa segna davvero le tue giornate.",
    about="Pixi è un tracker dell'umore in stile \"Year in Pixels\" con un gattino disegnato che ti chiede com'è andato ieri. Tocca un colore ed è fatta. Ogni giorno diventa un pixel, ogni anno un'immagine luminosa che ti piacerà guardare.",
    h_q="UNA DOMANDA, 15 SECONDI",
    q=["Un promemoria gentile ogni mattina", "Tocca un colore. Niente da scrivere, nessuna pressione", "Hai saltato un giorno? Compilalo dopo"],
    h_t="MOLTO PIÙ DELL'UMORE",
    t=["Modelli per umore, sonno, sogni, energia, ciclo, dolore, allenamento, alcol, meditazione, lettura, acqua, tempo davanti allo schermo, gratitudine e altro",
       "Oppure crea la tua mappa con la tua domanda, i tuoi colori e i tuoi livelli"],
    h_s="SCOPRI COSA VA INSIEME",
    s=["Pixi ti mostra quali colori compaiono insieme, come notti riposanti e giornate radiose",
       "Il tuo mese a confronto con il precedente e cosa spicca in ogni giorno della settimana"],
    h_p="IL TUO ANNO COME POSTER",
    p=["Ogni mappa come una ruota dell'anno, da condividere o da appendere al muro"],
    h_priv="PRIVATO PER SCELTA",
    priv=["Nessun account, nessuna pubblicità. I tuoi dati restano sul tuo dispositivo"],
    h_prem="PIXI PREMIUM",
    prem1="Pixi è gratis fino a 4 mappe. Pixi Premium sblocca mappe illimitate e tutte le statistiche: prova il piano mensile gratis per 3 giorni o paga una volta sola per l'accesso a vita.",
    prem2="L'abbonamento mensile si rinnova automaticamente se non viene disdetto almeno 24 ore prima della fine del periodo in corso. Il pagamento viene addebitato sul tuo account Apple. Puoi gestirlo o disdirlo nelle impostazioni del tuo account App Store.",
    terms="Condizioni d'uso",
    privacy="Informativa sulla privacy",
    contact="Domande o idee? Caspar, lo sviluppatore, legge ogni messaggio:",
)

PT_BR = dict(
    name="Pixi: Meu ano em pixels",
    subtitle="Diário de humor e emoções",
    keywords="sentimentos,hábitos,calendário,gato,fofo,sono,menstruação,sonhos,cores,autocuidado,estética",
    promo="Uma pergunta toda manhã, uma cor por dia. Veja seu ano virar uma imagem luminosa com o Pixi, o gatinho que pergunta como foi o seu dia ontem.",
    intro="Seu ano inteiro em uma só imagem. Uma pergunta toda manhã, uma cor por dia. Depois de algumas semanas, você vê o que realmente marca seus dias.",
    about="Pixi é um registro de humor no estilo \"Year in Pixels\" com um gatinho desenhado que pergunta como foi ontem. Toque em uma cor e pronto. Cada dia vira um pixel, cada ano uma imagem luminosa que você vai adorar olhar.",
    h_q="UMA PERGUNTA, 15 SEGUNDOS",
    q=["Um lembrete suave toda manhã", "Toque em uma cor. Nada para escrever, sem pressão", "Esqueceu um dia? Preencha depois"],
    h_t="MUITO ALÉM DO HUMOR",
    t=["Modelos para humor, sono, sonhos, energia, menstruação, dor, treino, álcool, meditação, leitura, água, tempo de tela, gratidão e mais",
       "Ou crie seu próprio mapa com sua pergunta, suas cores e seus níveis"],
    h_s="VEJA O QUE ANDA JUNTO",
    s=["O Pixi mostra quais cores aparecem juntas, como noites tranquilas e dias radiantes",
       "Seu mês comparado com o anterior e o que se destaca em cada dia da semana"],
    h_p="SEU ANO COMO PÔSTER",
    p=["Cada mapa como uma roda do ano, para compartilhar ou pendurar na parede"],
    h_priv="PRIVADO DESDE O INÍCIO",
    priv=["Sem conta, sem anúncios. Seus dados ficam no seu aparelho"],
    h_prem="PIXI PREMIUM",
    prem1="O Pixi é grátis com até 4 mapas. O Pixi Premium libera mapas ilimitados e todas as estatísticas: experimente o plano mensal grátis por 3 dias ou pague uma única vez para ter acesso vitalício.",
    prem2="A assinatura mensal é renovada automaticamente, a menos que seja cancelada pelo menos 24 horas antes do fim do período atual. O pagamento é cobrado na sua conta Apple. Você pode gerenciar ou cancelar nos ajustes da sua conta da App Store.",
    terms="Termos de uso",
    privacy="Política de privacidade",
    contact="Dúvidas ou ideias? Caspar, o desenvolvedor, lê todas as mensagens:",
)

PT_PT = dict(
    name="Pixi: O meu ano em píxeis",
    subtitle="Diário de humor e emoções",
    keywords="sentimentos,hábitos,calendário,gato,fofo,sono,menstruação,sonhos,cores,bem-estar,estética,registo",
    promo="Uma pergunta todas as manhãs, uma cor por dia. Vê o teu ano transformar-se numa imagem luminosa com o Pixi, o gatinho que te pergunta como correu ontem.",
    intro="O teu ano inteiro numa só imagem. Uma pergunta todas as manhãs, uma cor por dia. Ao fim de algumas semanas, vês o que realmente marca os teus dias.",
    about="O Pixi é um registo de humor ao estilo \"Year in Pixels\" com um gatinho desenhado que te pergunta como correu ontem. Toca numa cor e está feito. Cada dia torna-se um píxel, cada ano uma imagem luminosa que vais adorar ver.",
    h_q="UMA PERGUNTA, 15 SEGUNDOS",
    q=["Um lembrete suave todas as manhãs", "Toca numa cor. Nada para escrever, sem pressão", "Falhaste um dia? Preenche mais tarde"],
    h_t="MUITO MAIS DO QUE O HUMOR",
    t=["Modelos para humor, sono, sonhos, energia, menstruação, dor, treino, álcool, meditação, leitura, água, tempo de ecrã, gratidão e muito mais",
       "Ou cria o teu próprio mapa com a tua pergunta, as tuas cores e os teus níveis"],
    h_s="VÊ O QUE ANDA JUNTO",
    s=["O Pixi mostra que cores aparecem juntas, como noites repousantes e dias radiantes",
       "O teu mês comparado com o anterior e o que se destaca em cada dia da semana"],
    h_p="O TEU ANO COMO POSTER",
    p=["Cada mapa como uma roda do ano, para partilhar ou pendurar na parede"],
    h_priv="PRIVADO DESDE O INÍCIO",
    priv=["Sem conta, sem anúncios. Os teus dados ficam no teu dispositivo"],
    h_prem="PIXI PREMIUM",
    prem1="O Pixi é gratuito até 4 mapas. O Pixi Premium desbloqueia mapas ilimitados e todas as estatísticas: experimenta o plano mensal grátis durante 3 dias ou paga uma única vez para acesso vitalício.",
    prem2="A subscrição mensal renova-se automaticamente, a menos que seja cancelada pelo menos 24 horas antes do fim do período atual. O pagamento é cobrado na tua conta Apple. Podes geri-la ou cancelá-la nas definições da tua conta da App Store.",
    terms="Termos de utilização",
    privacy="Política de privacidade",
    contact="Dúvidas ou ideias? O Caspar, o programador, lê todas as mensagens:",
)

NL = dict(
    name="Pixi: Mijn jaar in pixels",
    subtitle="Stemmingsdagboek & tracker",
    keywords="emoties,gevoelens,dagboek,gewoontes,kalender,kat,schattig,slaap,menstruatie,dromen,kleuren,zelfzorg",
    promo="Elke ochtend één vraag, elke dag één kleur. Zie je jaar veranderen in een stralend beeld met Pixi, het katje dat vraagt hoe gisteren was.",
    intro="Je hele jaar in één beeld. Elke ochtend één vraag, elke dag één kleur. Na een paar weken zie je wat je dagen echt bepaalt.",
    about="Pixi is een stemmingstracker in \"Year in Pixels\" stijl met een getekend katje dat vraagt hoe gisteren was. Tik op een kleur, klaar. Elke dag wordt een pixel, elk jaar een stralend beeld waar je graag naar kijkt.",
    h_q="ÉÉN VRAAG, 15 SECONDEN",
    q=["Elke ochtend een zachte herinnering", "Tik op een kleur. Niets typen, geen druk", "Een dag gemist? Vul hem later in"],
    h_t="MEER DAN ALLEEN STEMMING",
    t=["Sjablonen voor stemming, slaap, dromen, energie, menstruatie, pijn, sport, alcohol, meditatie, lezen, water, schermtijd, dankbaarheid en meer",
       "Of maak je eigen map met je eigen vraag, kleuren en niveaus"],
    h_s="ZIE WAT BIJ ELKAAR HOORT",
    s=["Pixi laat zien welke kleuren samen voorkomen, zoals uitgeruste nachten en stralende dagen",
       "Je maand vergeleken met de vorige, en wat opvalt per dag van de week"],
    h_p="JE JAAR ALS POSTER",
    p=["Elke map als rond jaarwiel, om te delen of aan de muur te hangen"],
    h_priv="PRIVÉ VANAF HET BEGIN",
    priv=["Geen account, geen advertenties. Je gegevens blijven op je apparaat"],
    h_prem="PIXI PREMIUM",
    prem1="Pixi is gratis met maximaal 4 maps. Pixi Premium ontgrendelt onbeperkt maps en alle statistieken: probeer het maandabonnement 3 dagen gratis of betaal één keer voor levenslange toegang.",
    prem2="Het maandabonnement wordt automatisch verlengd, tenzij het minstens 24 uur voor het einde van de huidige periode wordt opgezegd. De betaling wordt afgeschreven van je Apple Account. Je kunt het beheren of opzeggen in de instellingen van je App Store account.",
    terms="Gebruiksvoorwaarden",
    privacy="Privacybeleid",
    contact="Vragen of ideeën? Caspar, de ontwikkelaar, leest elk bericht:",
)

CA = dict(
    name="Pixi: El meu any en píxels",
    subtitle="Diari d'estat d'ànim",
    keywords="emocions,sentiments,hàbits,calendari,gat,bonic,son,regla,somnis,colors,benestar,humor",
    promo="Una pregunta cada matí, un color cada dia. Mira com el teu any es converteix en una imatge lluminosa amb Pixi, el gatet que et pregunta com va anar ahir.",
    intro="Tot el teu any en una sola imatge. Una pregunta cada matí, un color cada dia. Al cap d'unes setmanes veus què marca de debò els teus dies.",
    about="Pixi és un registre de l'estat d'ànim a l'estil \"Year in Pixels\" amb un gatet dibuixat que et pregunta com va anar ahir. Toca un color i ja està. Cada dia esdevé un píxel i cada any una imatge lluminosa que t'encantarà mirar.",
    h_q="UNA PREGUNTA, 15 SEGONS",
    q=["Un recordatori suau cada matí", "Toca un color. Res a escriure, cap pressió", "T'has saltat un dia? Omple'l més tard"],
    h_t="MOLT MÉS QUE L'ESTAT D'ÀNIM",
    t=["Plantilles per a l'estat d'ànim, el son, els somnis, l'energia, la regla, el dolor, l'entrenament, l'alcohol, la meditació, la lectura, l'aigua, el temps de pantalla, la gratitud i més",
       "O crea el teu propi mapa amb la teva pregunta, els teus colors i els teus nivells"],
    h_s="DESCOBREIX QUÈ VA JUNT",
    s=["Pixi et mostra quins colors apareixen junts, com nits reparadores i dies radiants",
       "El teu mes comparat amb l'anterior i què destaca cada dia de la setmana"],
    h_p="EL TEU ANY COM A PÒSTER",
    p=["Cada mapa com una roda de l'any, per compartir o penjar a la paret"],
    h_priv="PRIVAT DES DEL PRINCIPI",
    priv=["Sense compte ni anuncis. Les teves dades es queden al teu dispositiu"],
    h_prem="PIXI PREMIUM",
    prem1="Pixi és gratuït amb fins a 4 mapes. Pixi Premium desbloqueja mapes il·limitats i totes les estadístiques: prova el pla mensual gratis durant 3 dies o paga una sola vegada per tenir-lo per sempre.",
    prem2="La subscripció mensual es renova automàticament tret que es cancel·li com a mínim 24 hores abans del final del període actual. El pagament es carrega al teu compte d'Apple. Pots gestionar-la o cancel·lar-la a la configuració del teu compte de l'App Store.",
    terms="Condicions d'ús",
    privacy="Política de privadesa",
    contact="Preguntes o idees? En Caspar, el desenvolupador, llegeix tots els missatges:",
)

GROUP_A = {
    "en-US": EN_US, "en-GB": EN_GB, "en-AU": EN_GB, "en-CA": EN_GB,
    "de-DE": DE, "fr-FR": FR, "fr-CA": FR, "es-ES": ES, "es-MX": ES_MX,
    "it": IT, "pt-BR": PT_BR, "pt-PT": PT_PT, "nl-NL": NL, "ca": CA,
}
