import 'package:flutter/widgets.dart';

/// Tiny localisation layer (DE/EN) without code generation.
///
/// Usage: `final s = S.of(context); Text(s.t('next'))`.
/// Map titles / questions / level labels stored as `@key` are resolved with
/// `s.r(text)` so user-typed free text passes through unchanged.
class S {
  S(this.locale);

  final Locale locale;

  static S of(BuildContext context) => S(Localizations.localeOf(context));

  bool get isDe => locale.languageCode == 'de';

  String t(String key) {
    final table = isDe ? _de : _en;
    return table[key] ?? _en[key] ?? key;
  }

  /// Resolve `@key` strings; free text passes through.
  String r(String text) {
    if (text.startsWith('@')) return t(text.substring(1));
    return text;
  }

  String withName(String key, String name) {
    final v = t(key);
    if (name.trim().isEmpty) {
      return v.replaceAll(', {name}', '').replaceAll(' {name}', '');
    }
    return v.replaceAll('{name}', name.trim());
  }

  List<String> get monthsShort => isDe
      ? const ['Jan', 'Feb', 'Mär', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dez']
      : const ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

  List<String> get monthsLong => isDe
      ? const ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember']
      : const ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

  List<String> get monthLetters => isDe
      ? const ['J', 'F', 'M', 'A', 'M', 'J', 'J', 'A', 'S', 'O', 'N', 'D']
      : const ['J', 'F', 'M', 'A', 'M', 'J', 'J', 'A', 'S', 'O', 'N', 'D'];

  List<String> get weekdaysShort => isDe
      ? const ['Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So']
      : const ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
}

const Map<String, String> _de = {
  // general
  'app_name': 'Pixi',
  'next': 'Weiter',
  'back': 'Zurück',
  'done': 'Fertig',
  'save': 'Speichern',
  'cancel': 'Abbrechen',
  'delete': 'Löschen',
  'skip': 'Überspringen',
  'later': 'Später',
  'ok': 'Okay',
  'yes': 'Ja',
  'no': 'Nein',
  'today': 'Heute',
  'yesterday': 'Gestern',
  'premium': 'Premium',
  'free': 'Kostenlos',

  // onboarding
  'ob_hi_title': 'Hi, ich bin Pixi.',
  'ob_hi_sub': 'Ich male dein Jahr. Jeden Tag ein Pixel – eine Frage, eine Farbe, fertig.',
  'ob_start': 'Los geht’s',
  'ob_name_title': 'Wie soll ich dich nennen?',
  'ob_name_sub': 'Nur damit ich dich morgens richtig begrüßen kann.',
  'ob_name_hint': 'Dein Name',
  'ob_pick_title': 'Womit fangen wir an, {name}?',
  'ob_pick_sub': 'Such dir deine erste Map aus. Mehr kannst du später jederzeit dazunehmen.',
  'ob_pick_choose': 'Diese nehme ich',
  'ob_how_title': 'So trägst du ein.',
  'ob_how_sub': 'Eine Frage, eine Farbe. Probier’s gleich aus – tipp auf eine Farbe.',
  'ob_how_done': 'Genau so. Das war dein erstes Pixel.',
  'ob_time_title': 'Jeden Morgen eine Frage.',
  'ob_time_sub': 'Ich frag dich morgens, wie gestern war. 15 Sekunden, dann bist du durch.',
  'ob_time_label': 'Erinnerung um',
  'ob_time_change': 'Zum Ändern tippen',
  'ob_circle_title': '…und als Kreis.',
  'ob_circle_sub': 'Dein Jahr als Rad – zum Teilen oder als Poster an die Wand.',
  'ob_stats_title': 'Deine Muster.',
  'ob_stats_sub': 'Bester Monat, schwächster Wochentag – nach ein paar Wochen siehst du, was dich bewegt.',
  'ob_corr_title': 'Maps übereinander.',
  'ob_corr_sub': 'Zwei Maps, ein Blick: Nach guten Nächten war deine Stimmung besser? Pixi rechnet das für dich aus.',
  'ob_corr_add': 'Noch eine Map dazunehmen',
  'ob_corr_added': 'Dabei',
  'ob_go_title': 'Fertig, {name}.',
  'ob_go_sub': 'Ich melde mich morgen früh. Versprochen.',
  'ob_go_notif': 'Erinnerungen erlauben',
  'ob_go_without': 'Ohne Erinnerung starten',

  // home / year
  'year_view': 'Jahr',
  'circle_view': 'Kreis',
  'stats': 'Statistik',
  'maps': 'Maps',
  'settings': 'Einstellungen',
  'checkin': 'Check-in',
  'checkin_cta': 'Wie war gestern?',
  'checkin_done_today': 'Heute erledigt ✓',
  'legend': 'Legende',
  'empty_year': 'Noch leer. Tipp auf einen Tag oder starte den Check-in.',
  'share': 'Teilen',
  'share_text': 'Mein Jahr in Pixeln – mit Pixi.',
  'day_title': 'Wie war der Tag?',
  'clear_entry': 'Eintrag löschen',
  'no_maps_title': 'Noch keine Map.',
  'no_maps_sub': 'Leg deine erste Map an – Stimmung, Träume, Training …',
  'add_map': 'Map hinzufügen',
  'days_filled': 'Tage eingetragen',
  'streak': 'Serie',
  'streak_days': '{n} Tage',

  // check-in
  'ci_title': 'Guten Morgen, {name}.',
  'ci_which_day': 'Für welchen Tag?',
  'ci_summary_title': 'Das war’s.',
  'ci_summary_sub': 'Bis morgen früh.',
  'ci_skip_map': 'Heute nicht',
  'ci_progress': '{a} von {b}',

  // maps
  'maps_title': 'Deine Maps',
  'new_map': 'Neue Map',
  'templates': 'Vorlagen',
  'cat_feelings': 'Gefühle',
  'cat_body': 'Körper',
  'cat_habits': 'Gewohnheiten',
  'cat_custom': 'Eigene',
  'custom_map': 'Eigene Map',
  'custom_map_sub': 'Frage, Farben und Titel selbst festlegen',
  'edit_map': 'Map bearbeiten',
  'map_title_label': 'Titel',
  'map_question_label': 'Frage am Morgen',
  'map_base_color': 'Grundfarbe',
  'map_levels': 'Stufen',
  'map_level_label': 'Bezeichnung',
  'add_level': 'Stufe hinzufügen',
  'delete_map': 'Map löschen',
  'delete_map_confirm': 'Wirklich löschen? Alle Einträge dieser Map gehen verloren.',
  'free_limit_title': 'Vier Maps sind frei.',
  'free_limit_sub': 'Mit Premium bekommst du unbegrenzt Maps, Statistiken und Zusammenhänge.',
  'reorder_hint': 'Halten und ziehen zum Sortieren',

  // stats
  'stats_title': 'Statistik',
  'best_month': 'Bester Monat',
  'worst_month': 'Schwächster Monat',
  'best_weekday': 'Bester Wochentag',
  'weakest_weekday': 'Schwächster Wochentag',
  'average': 'Durchschnitt',
  'distribution': 'Verteilung',
  'per_month': 'Pro Monat',
  'correlations': 'Zusammenhänge',
  'corr_pick': 'Vergleich mit',
  'corr_need_two': 'Für Zusammenhänge brauchst du zwei Maps mit Einträgen an denselben Tagen.',
  'corr_none': 'Noch kein klarer Zusammenhang – gib den Maps ein paar Wochen.',
  'corr_result_pos': 'An Tagen mit hohem „{a}“ war „{b}“ im Schnitt {d} Stufen höher.',
  'corr_result_neg': 'An Tagen mit hohem „{a}“ war „{b}“ im Schnitt {d} Stufen niedriger.',
  'corr_days': 'basierend auf {n} gemeinsamen Tagen',
  'stats_locked_title': 'Statistik ist Premium.',
  'stats_locked_sub': 'Monatsvergleich, Wochentage und Zusammenhänge zwischen deinen Maps.',
  'not_enough_data': 'Noch zu wenig Daten – trag ein paar Tage ein.',

  // premium
  'paywall_title': 'Pixi Premium',
  'paywall_sub': 'Einmal zahlen oder ein Jahr – kein Monatsabo.',
  'plan_year': 'Jahr',
  'plan_year_price': '14,99 €',
  'plan_year_sub': 'pro Jahr, jederzeit kündbar',
  'plan_life': 'Für immer',
  'plan_life_price': '29,99 €',
  'plan_life_sub': 'einmalig, gehört dir',
  'feat_maps': 'Unbegrenzt Maps',
  'feat_stats': 'Statistik & Zusammenhänge',
  'feat_support': 'Unterstützt eine kleine Katze',
  'buy': 'Freischalten',
  'restore': 'Käufe wiederherstellen',
  'premium_active': 'Premium ist aktiv. Danke!',
  'store_unavailable': 'Der Store ist gerade nicht erreichbar. Bitte später erneut versuchen.',
  'restore_none': 'Keine früheren Käufe gefunden.',
  'sub_disclosure': 'Das Jahresabo verlängert sich automatisch, wenn es nicht mindestens 24 Stunden vor Ablauf in den Einstellungen deines Apple-Accounts gekündigt wird. Die Zahlung erfolgt über deinen Apple-Account.',
  'terms': 'Nutzungsbedingungen',
  'privacy': 'Datenschutz',

  // settings
  'reminder': 'Erinnerung',
  'reminder_time': 'Uhrzeit',
  'reminder_on': 'Morgens erinnern',
  'your_name': 'Dein Name',
  'export': 'Daten exportieren',
  'about': 'Über Pixi',
  'version': 'Version',
  'feedback': 'Feedback geben',
  'rate': 'Pixi bewerten',
  'dev_toggle_premium': 'Premium (Test) umschalten',

  // feedback prompts
  'fb_map_title': 'Kurze Frage.',
  'fb_map_sub': 'Wie fühlt sich Pixi bis hierhin an?',
  'fb_checkin_title': 'Erstes Pixel gesetzt!',
  'fb_checkin_sub': 'War der Check-in angenehm?',
  'fb_good': 'Gut',
  'fb_meh': 'Geht so',
  'fb_bad': 'Nicht so',
  'fb_thanks': 'Danke – das hilft.',
  'fb_tell': 'Magst du kurz sagen, was besser sein könnte?',
  'fb_send': 'Abschicken',

  // template titles
  't_mood': 'Stimmung',
  't_cry': 'Geweint',
  't_anxiety': 'Anspannung',
  't_social': 'Soziales',
  't_gratitude': 'Dankbar',
  't_dreams': 'Träume',
  't_sleep': 'Schlaf',
  't_energy': 'Energie',
  't_period': 'Periode',
  't_pain': 'Schmerzen',
  't_training': 'Training',
  't_alcohol': 'Alkohol',
  't_meditation': 'Meditation',
  't_reading': 'Lesen',
  't_screen': 'Bildschirmzeit',
  't_water': 'Wasser',

  // template questions (asked in the morning about yesterday)
  'q_mood': 'Wie war deine Stimmung?',
  'q_cry': 'Hast du geweint?',
  'q_anxiety': 'Wie angespannt warst du?',
  'q_social': 'Wie viel warst du unter Leuten?',
  'q_gratitude': 'Gab es etwas, wofür du dankbar warst?',
  'q_dreams': 'Hast du geträumt?',
  'q_sleep': 'Wie hast du geschlafen?',
  'q_energy': 'Wie viel Energie hattest du?',
  'q_period': 'Periode?',
  'q_pain': 'Hattest du Schmerzen?',
  'q_training': 'Hast du trainiert?',
  'q_alcohol': 'Hast du Alkohol getrunken?',
  'q_meditation': 'Hast du meditiert?',
  'q_reading': 'Hast du gelesen?',
  'q_screen': 'Wie viel Bildschirmzeit?',
  'q_water': 'Genug getrunken?',

  // level labels
  'l_mood_0': 'Mies',
  'l_mood_1': 'Meh',
  'l_mood_2': 'Okay',
  'l_mood_3': 'Gut',
  'l_mood_4': 'Super',
  'l_cry_0': 'Nein',
  'l_cry_1': 'Ein bisschen',
  'l_cry_2': 'Viel',
  'l_anx_0': 'Entspannt',
  'l_anx_1': 'Leicht',
  'l_anx_2': 'Deutlich',
  'l_anx_3': 'Stark',
  'l_soc_0': 'Allein',
  'l_soc_1': 'Etwas',
  'l_soc_2': 'Viel',
  'l_dr_0': 'Keiner',
  'l_dr_1': 'Vage',
  'l_dr_2': 'Lebhaft',
  'l_dr_3': 'Intensiv',
  'l_sl_0': 'Schlecht',
  'l_sl_1': 'Unruhig',
  'l_sl_2': 'Okay',
  'l_sl_3': 'Gut',
  'l_sl_4': 'Tief',
  'l_en_0': 'Leer',
  'l_en_1': 'Wenig',
  'l_en_2': 'Gut',
  'l_en_3': 'Voll',
  'l_pe_0': 'Nein',
  'l_pe_1': 'Leicht',
  'l_pe_2': 'Mittel',
  'l_pe_3': 'Stark',
  'l_pa_0': 'Keine',
  'l_pa_1': 'Leicht',
  'l_pa_2': 'Mittel',
  'l_pa_3': 'Stark',
  'l_tr_0': 'Pause',
  'l_tr_1': 'Leicht',
  'l_tr_2': 'Hart',
  'l_al_0': 'Nichts',
  'l_al_1': 'Ein Glas',
  'l_al_2': 'Mehr',
  'l_rd_1': 'Kurz',
  'l_rd_2': 'Lange',
  'l_sc_0': 'Wenig',
  'l_sc_1': 'Normal',
  'l_sc_2': 'Zu viel',
  'l_wa_0': 'Zu wenig',
  'l_wa_1': 'Okay',
  'l_wa_2': 'Viel',
  'l_yes': 'Ja',
  'l_no': 'Nein',
  'l_low': 'Wenig',
  'l_mid': 'Mittel',
  'l_high': 'Viel',

  // notification
  'notif_title': 'Wie war gestern, {name}?',
  'notif_body': 'Ein Pixel, 15 Sekunden. Pixi wartet.',
};

const Map<String, String> _en = {
  'app_name': 'Pixi',
  'next': 'Next',
  'back': 'Back',
  'done': 'Done',
  'save': 'Save',
  'cancel': 'Cancel',
  'delete': 'Delete',
  'skip': 'Skip',
  'later': 'Later',
  'ok': 'Okay',
  'yes': 'Yes',
  'no': 'No',
  'today': 'Today',
  'yesterday': 'Yesterday',
  'premium': 'Premium',
  'free': 'Free',

  'ob_hi_title': 'Hi, I’m Pixi.',
  'ob_hi_sub': 'I paint your year. One pixel a day – one question, one colour, done.',
  'ob_start': 'Let’s go',
  'ob_name_title': 'What should I call you?',
  'ob_name_sub': 'Just so I can greet you properly in the morning.',
  'ob_name_hint': 'Your name',
  'ob_pick_title': 'Where do we start, {name}?',
  'ob_pick_sub': 'Pick your first map. You can add more any time.',
  'ob_pick_choose': 'This one',
  'ob_how_title': 'This is how you log.',
  'ob_how_sub': 'One question, one colour. Try it – tap a colour.',
  'ob_how_done': 'Exactly. That was your first pixel.',
  'ob_time_title': 'One question every morning.',
  'ob_time_sub': 'I’ll ask you in the morning how yesterday was. 15 seconds and you’re done.',
  'ob_time_label': 'Reminder at',
  'ob_time_change': 'Tap to change',
  'ob_circle_title': '…and as a circle.',
  'ob_circle_sub': 'Your year as a wheel – to share, or as a poster on the wall.',
  'ob_stats_title': 'Your patterns.',
  'ob_stats_sub': 'Best month, weakest weekday – after a few weeks you’ll see what moves you.',
  'ob_corr_title': 'Maps on top of each other.',
  'ob_corr_sub': 'Two maps, one glance: better mood after good nights? Pixi does the math.',
  'ob_corr_add': 'Add another map',
  'ob_corr_added': 'Added',
  'ob_go_title': 'All set, {name}.',
  'ob_go_sub': 'I’ll check in tomorrow morning. Promise.',
  'ob_go_notif': 'Allow reminders',
  'ob_go_without': 'Start without reminder',

  'year_view': 'Year',
  'circle_view': 'Circle',
  'stats': 'Stats',
  'maps': 'Maps',
  'settings': 'Settings',
  'checkin': 'Check-in',
  'checkin_cta': 'How was yesterday?',
  'checkin_done_today': 'Done for today ✓',
  'legend': 'Legend',
  'empty_year': 'Still empty. Tap a day or start the check-in.',
  'share': 'Share',
  'share_text': 'My year in pixels – with Pixi.',
  'day_title': 'How was the day?',
  'clear_entry': 'Clear entry',
  'no_maps_title': 'No map yet.',
  'no_maps_sub': 'Create your first map – mood, dreams, training …',
  'add_map': 'Add map',
  'days_filled': 'days logged',
  'streak': 'Streak',
  'streak_days': '{n} days',

  'ci_title': 'Good morning, {name}.',
  'ci_which_day': 'Which day?',
  'ci_summary_title': 'That’s it.',
  'ci_summary_sub': 'See you tomorrow morning.',
  'ci_skip_map': 'Not today',
  'ci_progress': '{a} of {b}',

  'maps_title': 'Your maps',
  'new_map': 'New map',
  'templates': 'Templates',
  'cat_feelings': 'Feelings',
  'cat_body': 'Body',
  'cat_habits': 'Habits',
  'cat_custom': 'Custom',
  'custom_map': 'Custom map',
  'custom_map_sub': 'Set your own question, colours and title',
  'edit_map': 'Edit map',
  'map_title_label': 'Title',
  'map_question_label': 'Morning question',
  'map_base_color': 'Base colour',
  'map_levels': 'Levels',
  'map_level_label': 'Label',
  'add_level': 'Add level',
  'delete_map': 'Delete map',
  'delete_map_confirm': 'Really delete? All entries of this map will be lost.',
  'free_limit_title': 'Four maps are free.',
  'free_limit_sub': 'Premium gives you unlimited maps, statistics and correlations.',
  'reorder_hint': 'Hold and drag to reorder',

  'stats_title': 'Statistics',
  'best_month': 'Best month',
  'worst_month': 'Weakest month',
  'best_weekday': 'Best weekday',
  'weakest_weekday': 'Weakest weekday',
  'average': 'Average',
  'distribution': 'Distribution',
  'per_month': 'Per month',
  'correlations': 'Correlations',
  'corr_pick': 'Compare with',
  'corr_need_two': 'Correlations need two maps with entries on the same days.',
  'corr_none': 'No clear correlation yet – give the maps a few weeks.',
  'corr_result_pos': 'On days with high “{a}”, “{b}” was {d} levels higher on average.',
  'corr_result_neg': 'On days with high “{a}”, “{b}” was {d} levels lower on average.',
  'corr_days': 'based on {n} shared days',
  'stats_locked_title': 'Statistics are Premium.',
  'stats_locked_sub': 'Monthly comparison, weekdays and correlations between your maps.',
  'not_enough_data': 'Not enough data yet – log a few days.',

  'paywall_title': 'Pixi Premium',
  'paywall_sub': 'Pay once or per year – no monthly subscription.',
  'plan_year': 'Yearly',
  'plan_year_price': '\$14.99',
  'plan_year_sub': 'per year, cancel any time',
  'plan_life': 'Lifetime',
  'plan_life_price': '\$29.99',
  'plan_life_sub': 'one-time, yours forever',
  'feat_maps': 'Unlimited maps',
  'feat_stats': 'Statistics & correlations',
  'feat_support': 'Supports a small cat',
  'buy': 'Unlock',
  'restore': 'Restore purchases',
  'premium_active': 'Premium is active. Thank you!',
  'store_unavailable': 'The store is not reachable right now. Please try again later.',
  'restore_none': 'No previous purchases found.',
  'sub_disclosure': 'The yearly plan renews automatically unless cancelled at least 24 hours before the end of the period in your Apple account settings. Payment is charged to your Apple account.',
  'terms': 'Terms of Use',
  'privacy': 'Privacy Policy',

  'reminder': 'Reminder',
  'reminder_time': 'Time',
  'reminder_on': 'Remind me in the morning',
  'your_name': 'Your name',
  'export': 'Export data',
  'about': 'About Pixi',
  'version': 'Version',
  'feedback': 'Send feedback',
  'rate': 'Rate Pixi',
  'dev_toggle_premium': 'Toggle Premium (test)',

  'fb_map_title': 'Quick question.',
  'fb_map_sub': 'How does Pixi feel so far?',
  'fb_checkin_title': 'First pixel placed!',
  'fb_checkin_sub': 'Was the check-in pleasant?',
  'fb_good': 'Good',
  'fb_meh': 'So-so',
  'fb_bad': 'Not really',
  'fb_thanks': 'Thanks – that helps.',
  'fb_tell': 'Care to tell us what could be better?',
  'fb_send': 'Send',

  't_mood': 'Mood',
  't_cry': 'Cried',
  't_anxiety': 'Anxiety',
  't_social': 'Social',
  't_gratitude': 'Grateful',
  't_dreams': 'Dreams',
  't_sleep': 'Sleep',
  't_energy': 'Energy',
  't_period': 'Period',
  't_pain': 'Pain',
  't_training': 'Training',
  't_alcohol': 'Alcohol',
  't_meditation': 'Meditation',
  't_reading': 'Reading',
  't_screen': 'Screen time',
  't_water': 'Water',

  'q_mood': 'How was your mood?',
  'q_cry': 'Did you cry?',
  'q_anxiety': 'How anxious were you?',
  'q_social': 'How much were you around people?',
  'q_gratitude': 'Anything you were grateful for?',
  'q_dreams': 'Did you dream?',
  'q_sleep': 'How did you sleep?',
  'q_energy': 'How much energy did you have?',
  'q_period': 'Period?',
  'q_pain': 'Were you in pain?',
  'q_training': 'Did you train?',
  'q_alcohol': 'Did you drink alcohol?',
  'q_meditation': 'Did you meditate?',
  'q_reading': 'Did you read?',
  'q_screen': 'How much screen time?',
  'q_water': 'Drank enough?',

  'l_mood_0': 'Awful',
  'l_mood_1': 'Meh',
  'l_mood_2': 'Okay',
  'l_mood_3': 'Good',
  'l_mood_4': 'Great',
  'l_cry_0': 'No',
  'l_cry_1': 'A little',
  'l_cry_2': 'A lot',
  'l_anx_0': 'Calm',
  'l_anx_1': 'Slightly',
  'l_anx_2': 'Clearly',
  'l_anx_3': 'Strongly',
  'l_soc_0': 'Alone',
  'l_soc_1': 'Some',
  'l_soc_2': 'A lot',
  'l_dr_0': 'None',
  'l_dr_1': 'Vague',
  'l_dr_2': 'Vivid',
  'l_dr_3': 'Intense',
  'l_sl_0': 'Bad',
  'l_sl_1': 'Restless',
  'l_sl_2': 'Okay',
  'l_sl_3': 'Good',
  'l_sl_4': 'Deep',
  'l_en_0': 'Empty',
  'l_en_1': 'Low',
  'l_en_2': 'Good',
  'l_en_3': 'Full',
  'l_pe_0': 'No',
  'l_pe_1': 'Light',
  'l_pe_2': 'Medium',
  'l_pe_3': 'Heavy',
  'l_pa_0': 'None',
  'l_pa_1': 'Mild',
  'l_pa_2': 'Medium',
  'l_pa_3': 'Strong',
  'l_tr_0': 'Rest',
  'l_tr_1': 'Light',
  'l_tr_2': 'Hard',
  'l_al_0': 'None',
  'l_al_1': 'One drink',
  'l_al_2': 'More',
  'l_rd_1': 'A bit',
  'l_rd_2': 'A lot',
  'l_sc_0': 'Little',
  'l_sc_1': 'Normal',
  'l_sc_2': 'Too much',
  'l_wa_0': 'Too little',
  'l_wa_1': 'Okay',
  'l_wa_2': 'Plenty',
  'l_yes': 'Yes',
  'l_no': 'No',
  'l_low': 'Low',
  'l_mid': 'Medium',
  'l_high': 'High',

  'notif_title': 'How was yesterday, {name}?',
  'notif_body': 'One pixel, 15 seconds. Pixi is waiting.',
};
