import 'package:flutter/widgets.dart';

/// Tiny localisation layer (DE/EN) without code generation.
///
/// Usage: `final s = S.of(context); Text(s.t('next'))`.
/// Map titles / questions / level labels stored as `@key` are resolved with
/// `s.r(text)` so user-typed free text passes through unchanged.
class S {
  S(this.locale);

  final Locale locale;

  static S of(BuildContext context) => S(Localizations.localeOf(context));

  bool get isDe => locale.languageCode == 'de';

  String t(String key) {
    final table = isDe ? _de : _en;
    return table[key] ?? _en[key] ?? key;
  }

  /// Resolve `@key` strings; free text passes through.
  String r(String text) {
    if (text.startsWith('@')) return t(text.substring(1));
    return text;
  }

  String withName(String key, String name) {
    final v = t(key);
    if (name.trim().isEmpty) {
      return v.replaceAll(', {name}', '').replaceAll(' {name}', '');
    }
    return v.replaceAll('{name}', name.trim());
  }

  List<String> get monthsShort => isDe
      ? const ['Jan', 'Feb', 'Mär', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dez']
      : const ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

  List<String> get monthsLong => isDe
      ? const ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember']
      : const ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

  List<String> get monthLetters => isDe
      ? const ['J', 'F', 'M', 'A', 'M', 'J', 'J', 'A', 'S', 'O', 'N', 'D']
      : const ['J', 'F', 'M', 'A', 'M', 'J', 'J', 'A', 'S', 'O', 'N', 'D'];

  List<String> get weekdaysShort => isDe
      ? const ['Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So']
      : const ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

  /// "An Montagen …" / "On Mondays …"
  List<String> get weekdaysPlural => isDe
      ? const ['Montagen', 'Dienstagen', 'Mittwochen', 'Donnerstagen', 'Freitagen', 'Samstagen', 'Sonntagen']
      : const ['Mondays', 'Tuesdays', 'Wednesdays', 'Thursdays', 'Fridays', 'Saturdays', 'Sundays'];
}

const Map<String, String> _de = {
  // general
  'app_name': 'Pixi',
  'next': 'Weiter',
  'back': 'Zurück',
  'done': 'Fertig',
  'save': 'Speichern',
  'cancel': 'Abbrechen',
  'delete': 'Löschen',
  'skip': 'Überspringen',
  'later': 'Später',
  'ok': 'Okay',
  'yes': 'Ja',
  'no': 'Nein',
  'today': 'Heute',
  'yesterday': 'Gestern',
  'premium': 'Premium',
  'free': 'Kostenlos',

  // onboarding
  'ob_hi_title': 'Hi, ich bin Pixi.',
  'ob_hi_sub': 'Ich male dein Jahr. Jeden Tag ein Pixel: eine Frage, eine Farbe, fertig.',
  'ob_start': 'Los geht’s',
  'ob_name_title': 'Wie soll ich dich nennen?',
  'ob_name_sub': 'Nur damit ich dich morgens richtig begrüßen kann.',
  'ob_name_hint': 'Dein Name',
  'ob_pick_title': 'Womit fangen wir an, {name}?',
  'ob_pick_sub': 'Such dir deine erste Map aus. Mehr kannst du später jederzeit dazunehmen.',
  'ob_pick_choose': 'Diese nehme ich',
  'ob_how_title': 'So trägst du ein.',
  'ob_how_sub': 'Eine Frage, eine Farbe. Probier’s gleich aus und tipp auf eine Farbe.',
  'ob_how_done': 'Genau so. Das war dein erstes Pixel.',
  'ob_time_title': 'Jeden Morgen eine Frage.',
  'ob_time_sub': 'Ich frag dich morgens, wie gestern war. 15 Sekunden, dann bist du durch.',
  'ob_time_label': 'Erinnerung um',
  'ob_time_change': 'Zum Ändern tippen',
  'ob_circle_title': '…und als Kreis.',
  'ob_circle_sub': 'Dein Jahr als Rad. Zum Teilen oder als Poster an die Wand.',
  'ob_stats_title': 'Deine Muster.',
  'ob_stats_sub': 'Welche Farben diesen Monat öfter auftauchen als im letzten und was an welchem Wochentag besonders oft vorkommt.',
  'ob_corr_title': 'Maps übereinander.',
  'ob_corr_sub': 'Pixi findet, welche Farben zusammengehören. Zum Beispiel erholsame Nächte und strahlende Tage.',
  'ob_corr_add': 'Lass uns gleich noch weitere Dinge tracken, um Korrelationen zu erkennen.',
  'ob_corr_added': 'Dabei',
  'ob_go_title': 'Fertig, {name}.',
  'ob_go_sub': 'Ich melde mich morgen früh. Versprochen.',
  'ob_go_notif': 'Erinnerungen erlauben',
  'ob_time_notif': 'Erinnerung aktivieren',
  'ob_time_later': 'Vielleicht später',
  'ob_go_start': 'Los geht’s',
  'ob_go_without': 'Ohne Erinnerung starten',

  // home / year
  'year_view': 'Jahr',
  'circle_view': 'Kreis',
  'stats': 'Statistik',
  'maps': 'Maps',
  'settings': 'Einstellungen',
  'checkin': 'Check-in',
  'checkin_cta': 'Wie war gestern?',
  'checkin_cta_today': 'Wie war heute?',
  'checkin_done_today': 'Heute erledigt ✓',
  'legend': 'Legende',
  'empty_year': 'Noch leer. Tipp auf einen Tag oder starte den Check-in.',
  'share': 'Teilen',
  'share_text': 'Mein Jahr in Pixeln, gemalt mit Pixi.',
  'day_title': 'Wie war der Tag?',
  'clear_entry': 'Eintrag löschen',
  'no_maps_title': 'Noch keine Map.',
  'no_maps_sub': 'Leg deine erste Map an: Stimmung, Träume, Training …',
  'add_map': 'Map hinzufügen',
  'days_filled': 'Tage eingetragen',
  'streak': 'Serie',
  'streak_days': '{n} Tage',

  // check-in
  'ci_title': 'Guten Morgen, {name}.',
  'ci_which_day': 'Für welchen Tag?',
  'ci_summary_title': 'Das war’s.',
  'ci_summary_sub': 'Bis morgen früh.',
  'ci_skip_map': 'Heute nicht',
  'ci_progress': '{a} von {b}',

  // maps
  'maps_title': 'Deine Maps',
  'new_map': 'Neue Map',
  'templates': 'Vorlagen',
  'cat_feelings': 'Gefühle',
  'cat_body': 'Körper',
  'cat_habits': 'Gewohnheiten',
  'cat_custom': 'Eigene',
  'custom_map': 'Eigene Map',
  'custom_map_sub': 'Frage, Farben und Titel selbst festlegen',
  'edit_map': 'Map bearbeiten',
  'map_title_label': 'Titel',
  'map_question_label': 'Frage am Morgen',
  'map_base_color': 'Grundfarbe',
  'map_cat': 'Katze',
  'map_cat_sub': 'Wer begleitet dich bei dieser Map?',
  'cat_neutral': 'Neutral',
  'cat_stretch': 'Streckt sich',
  'cat_happy': 'Fröhlich',
  'cat_wave': 'Winkt',
  'cat_curious': 'Neugierig',
  'cat_gym': 'Sport',
  'cat_sleep': 'Schläft',
  'cat_sad': 'Traurig',
  'cat_bell': 'Wecker',
  'cat_dreams': 'Träumt',
  'cat_period': 'Eingekuschelt',
  'cat_alcohol': 'Mit Cocktail',
  'cat_social': 'Kuschelt',
  'cat_pain': 'Hat Schmerzen',
  'cat_screen': 'Am Handy',
  'cat_gratitude': 'Dankbar',
  'cat_energy': 'Voller Energie',
  'cat_anxiety': 'Ängstlich',
  'cat_reading': 'Liest',
  'cat_water': 'Trinkt',
  'cat_meditation': 'Meditiert',
  'this_month': 'Dieser Monat',
  'this_month_sub': 'Wie oft welche Farbe und die Veränderung zum Vormonat',
  'vs_last_month': 'zum Vormonat',
  'month_no_data': 'Diesen Monat noch nichts eingetragen.',
  'days_short': 'Tage',
  'ob_plan_title': 'Pixi ganz freischalten?',
  'ob_plan_sub': 'Alle Maps, Statistiken und Zusammenhänge. Die ersten 3 Tage sind kostenlos.',
  'ob_plan_later': 'Erst mal kostenlos starten',
  'ob_plan_cta': 'Freischalten',
  'map_levels': 'Stufen',
  'map_level_label': 'Bezeichnung',
  'add_level': 'Stufe hinzufügen',
  'delete_map': 'Map löschen',
  'delete_map_confirm': 'Wirklich löschen? Alle Einträge dieser Map gehen verloren.',
  'free_limit_title': 'Vier Maps sind frei.',
  'free_limit_sub': 'Mit Premium bekommst du unbegrenzt Maps, Statistiken und Zusammenhänge.',
  'reorder_hint': 'Halten und ziehen zum Sortieren',

  // stats
  'stats_title': 'Statistik',
  'best_month': 'Bester Monat',
  'worst_month': 'Schwächster Monat',
  'best_weekday': 'Bester Wochentag',
  'weakest_weekday': 'Schwächster Wochentag',
  'average': 'Durchschnitt',
  'distribution': 'Verteilung',
  'per_month': 'Pro Monat',
  'pw_prev_title': 'Das zeigt dir Premium',
  'pw_links_why': 'Finde heraus, was dir guttut: Welche Farben tauchen zusammen auf? Workout-Tage und strahlende Stimmung, unruhige Nächte und graue Tage.',
  'pw_month_title': 'Dein Monat in Farben',
  'pw_month_why': 'Sieh auf einen Blick, welche Farben diesen Monat öfter auftauchen als im letzten.',
  'pw_week_title': 'Dein Wochenrhythmus',
  'pw_week_why': 'Welcher Wochentag bringt welche Farbe? Kleine Muster, große Wirkung.',
  'links_title': 'Was zusammengehört',
  'links_sub': 'Farben, die auffällig oft am selben Tag auftauchen. Die 10 stärksten aus all deinen Maps.',
  'links_none': 'Noch keine klaren Muster. Logge ein paar Wochen mehrere Maps, dann siehst du hier, was zusammengehört.',
  'correlations': 'Zusammenhänge',
  'corr_pick': 'Vergleich mit',
  'corr_need_two': 'Für Zusammenhänge brauchst du mindestens zwei Maps mit Einträgen an denselben Tagen.',
  'corr_none': 'Noch kein klarer Zusammenhang. Gib den Maps ein paar Wochen.',
  'corr_result_pos': 'An Tagen mit hohem „{a}“ war „{b}“ im Schnitt {d} Stufen höher.',
  'corr_result_neg': 'An Tagen mit hohem „{a}“ war „{b}“ im Schnitt {d} Stufen niedriger.',
  'corr_days': 'basierend auf {n} gemeinsamen Tagen',
  'stats_locked_title': 'Statistik ist Premium.',
  'stats_locked_sub': 'Was zusammengehört, dein Monat im Vergleich zum letzten und deine Wochentage.',
  'not_enough_data': 'Noch zu wenig Daten. Trag ein paar Tage ein.',

  // premium
  'paywall_title': 'Pixi Premium',
  'paywall_sub': '3 Tage kostenlos testen, danach monatlich kündbar. Oder einmal zahlen und Pixi für immer behalten.',
  'plan_year': 'Jahr',
  'plan_year_price': '14,99 €',
  'plan_year_sub': 'pro Jahr, jederzeit kündbar',
  'plan_life': 'Für immer',
  'plan_life_price': '34,99 €',
  'plan_life_sub': 'einmalig zahlen, gehört dir',
  'feat_maps': 'Unbegrenzt Maps',
  'feat_stats': 'Statistik & Zusammenhänge',
  'feat_support': 'Unterstützt eine kleine Katze',
  'buy': 'Freischalten',
  'restore': 'Käufe wiederherstellen',
  'premium_active': 'Premium ist aktiv. Danke!',
  'store_unavailable': 'Der Store ist gerade nicht erreichbar. Bitte später erneut versuchen.',
  'restore_none': 'Keine früheren Käufe gefunden.',
  'sub_disclosure': 'Nach der kostenlosen Testphase von 3 Tagen verlängert sich das Monatsabo automatisch für {price} im Monat, wenn du es nicht mindestens 24 Stunden vor Ablauf in den Einstellungen deines Apple-Accounts kündigst. Die Zahlung erfolgt über deinen Apple-Account.',
  'terms': 'Nutzungsbedingungen',
  'privacy': 'Datenschutz',

  // settings
  'reminder': 'Erinnerung',
  'reminder_time': 'Uhrzeit',
  'reminder_on': 'Morgens erinnern',
  'your_name': 'Dein Name',
  'export': 'Daten exportieren',
  'about': 'Über Pixi',
  'version': 'Version',
  'feedback': 'Feedback geben',
  'rate': 'Pixi bewerten',
  'dev_toggle_premium': 'Premium (Test) umschalten',

  // feedback prompts
  'fb_map_title': 'Kurze Frage.',
  'fb_map_sub': 'Wie fühlt sich Pixi bis hierhin an?',
  'fb_checkin_title': 'Erstes Pixel gesetzt!',
  'fb_checkin_sub': 'War der Check-in angenehm?',
  'fb_good': 'Gut',
  'fb_meh': 'Geht so',
  'fb_bad': 'Nicht so',
  'fb_thanks': 'Danke, das hilft.',
  'fb_tell': 'Magst du kurz sagen, was besser sein könnte?',
  'fb_send': 'Abschicken',

  // template titles
  't_mood': 'Stimmung',
  't_cry': 'Geweint',
  't_anxiety': 'Anspannung',
  't_social': 'Soziales',
  't_gratitude': 'Dankbar',
  't_dreams': 'Träume',
  't_sleep': 'Schlaf',
  't_energy': 'Energie',
  't_period': 'Periode',
  't_pain': 'Schmerzen',
  't_training': 'Training',
  't_alcohol': 'Alkohol',
  't_meditation': 'Meditation',
  't_reading': 'Lesen',
  't_screen': 'Bildschirmzeit',
  't_water': 'Wasser',

  // template questions (asked in the morning about yesterday)
  'q_mood': 'Wie war deine Stimmung?',
  'q_cry': 'Hast du geweint?',
  'q_anxiety': 'Wie angespannt warst du?',
  'q_social': 'Wie viel warst du unter Leuten?',
  'q_gratitude': 'Gab es etwas, wofür du dankbar warst?',
  'q_dreams': 'Hast du geträumt?',
  'q_sleep': 'Wie hast du geschlafen?',
  'q_energy': 'Wie viel Energie hattest du?',
  'q_period': 'Periode?',
  'q_pain': 'Hattest du Schmerzen?',
  'q_training': 'Hast du trainiert?',
  'q_alcohol': 'Hast du Alkohol getrunken?',
  'q_meditation': 'Hast du meditiert?',
  'q_reading': 'Hast du gelesen?',
  'q_screen': 'Wie viel Bildschirmzeit?',
  'q_water': 'Genug getrunken?',

  // level labels
  'l_mood_0': 'Stürmisch',
  'l_mood_1': 'Grau',
  'l_mood_2': 'Ruhig',
  'l_mood_3': 'Gut',
  'l_mood_4': 'Strahlend',
  'l_cry_0': 'Trocken',
  'l_cry_1': 'Feuchte Augen',
  'l_cry_2': 'Geweint',
  'l_cry_3': 'Wasserfall',
  'l_anx_0': 'Tiefenentspannt',
  'l_anx_1': 'Etwas nervös',
  'l_anx_2': 'Angespannt',
  'l_anx_3': 'Panik',
  'l_soc_0': 'Me-Time',
  'l_soc_1': 'Kurz gequatscht',
  'l_soc_2': 'Gute Gespräche',
  'l_soc_3': 'Unter Leuten',
  'l_gr_0': 'Nicht heute',
  'l_gr_1': 'Ein bisschen',
  'l_gr_2': 'Sehr dankbar',
  'l_dr_0': 'Keiner',
  'l_dr_1': 'Friedlich',
  'l_dr_2': 'Abenteuerlich',
  'l_dr_3': 'Surreal',
  'l_dr_4': 'Romantisch',
  'l_dr_5': 'Albtraum',
  'l_sl_0': 'Wach gelegen',
  'l_sl_1': 'Unruhig',
  'l_sl_2': 'Okay',
  'l_sl_3': 'Erholsam',
  'l_sl_4': 'Wie ein Stein',
  'l_en_0': 'Akku leer',
  'l_en_1': 'Schlapp',
  'l_en_2': 'Wach',
  'l_en_3': 'Aufgedreht',
  'l_pe_0': 'Keine',
  'l_pe_1': 'Schmierblutung',
  'l_pe_2': 'Leicht',
  'l_pe_3': 'Mittel',
  'l_pe_4': 'Stark',
  'l_pa_0': 'Schmerzfrei',
  'l_pa_1': 'Zwicken',
  'l_pa_2': 'Spürbar',
  'l_pa_3': 'Heftig',
  'l_tr_0': 'Couch-Tag',
  'l_tr_1': 'Spaziergang',
  'l_tr_2': 'Workout',
  'l_tr_3': 'Beast Mode',
  'l_al_0': 'Nüchtern',
  'l_al_1': 'Ein Glas',
  'l_al_2': 'Beschwipst',
  'l_al_3': 'Kater-Garantie',
  'l_me_0': 'Nicht heute',
  'l_me_1': 'Kurz',
  'l_me_2': 'Tief versunken',
  'l_rd_0': 'Nichts',
  'l_rd_1': 'Ein paar Seiten',
  'l_rd_2': 'Versunken',
  'l_sc_0': 'Digital Detox',
  'l_sc_1': 'Normal',
  'l_sc_2': 'Zu viel',
  'l_sc_3': 'Doomscrolling',
  'l_wa_0': 'Ausgedörrt',
  'l_wa_1': 'Okay',
  'l_wa_2': 'Gut getrunken',
  'l_yes': 'Ja',
  'l_no': 'Nein',
  'l_low': 'Wenig',
  'l_mid': 'Mittel',
  'l_high': 'Viel',

  // notification
  'notif_title': 'Wie war gestern, {name}?',
  'notif_body': 'Ein Pixel, 15 Sekunden. Pixi wartet.',
  'plan_month': 'Monatlich',
  'plan_month_price': '12,99 €',
  'plan_month_sub': '3 Tage kostenlos, danach {price} im Monat',
  'plan_month_sub_notrial': '{price} im Monat, monatlich kündbar',
  'plan_trial_badge': '3 Tage gratis',
  'cta_trial': 'Kostenlos testen',
  'cta_life': 'Für immer freischalten',
  'day_short1': 'Tag',
  'pat_more': '{n} Tage mehr „{l}“',
  'pat_more1': '1 Tag mehr „{l}“',
  'pat_less': '{n} Tage weniger „{l}“',
  'pat_less1': '1 Tag weniger „{l}“',
  'pat_than': 'als im {m}.',
  'pat_same': 'Genau die gleichen Farben wie im {m}.',
  'pat_first_month': 'Dein erster Monat in Farben.',
  'pat_week_title': 'Deine Wochentage',
  'pat_week_sub': 'Welche Farbe an welchem Wochentag besonders oft auftaucht',
  'pat_week_line': 'An {wd} ist „{l}“ besonders oft aufgetreten.',
  'pat_week_row': '„{l}“ besonders oft',
  'pat_week_none': 'nichts Auffälliges',
  'pat_year_title': 'Dein Jahr in Farben',
  'ob_support_title': 'Eine kleine Bitte.',
  'ob_support_sub': 'Ich bin Caspar und baue Pixi ganz allein. Über eine Bewertung von dir würde ich mich riesig freuen. Das hält mich motiviert, weiter an Pixi zu arbeiten.',
  'ob_support_rate': 'Pixi bewerten',
  'ob_support_skip': 'Jetzt nicht',
  'fb_streak_title': '3 Tage am Stück!',
  'fb_streak_sub': 'Wie gefällt dir Pixi bisher?',
  'follow_x': 'Folge mir auf X',
  'share_failed': 'Teilen hat gerade nicht geklappt. Bitte versuch es nochmal.',
};

const Map<String, String> _en = {
  'app_name': 'Pixi',
  'next': 'Next',
  'back': 'Back',
  'done': 'Done',
  'save': 'Save',
  'cancel': 'Cancel',
  'delete': 'Delete',
  'skip': 'Skip',
  'later': 'Later',
  'ok': 'Okay',
  'yes': 'Yes',
  'no': 'No',
  'today': 'Today',
  'yesterday': 'Yesterday',
  'premium': 'Premium',
  'free': 'Free',

  'ob_hi_title': 'Hi, I’m Pixi.',
  'ob_hi_sub': 'I paint your year. One pixel a day: one question, one colour, done.',
  'ob_start': 'Let’s go',
  'ob_name_title': 'What should I call you?',
  'ob_name_sub': 'Just so I can greet you properly in the morning.',
  'ob_name_hint': 'Your name',
  'ob_pick_title': 'Where do we start, {name}?',
  'ob_pick_sub': 'Pick your first map. You can add more any time.',
  'ob_pick_choose': 'This one',
  'ob_how_title': 'This is how you log.',
  'ob_how_sub': 'One question, one colour. Try it and tap a colour.',
  'ob_how_done': 'Exactly. That was your first pixel.',
  'ob_time_title': 'One question every morning.',
  'ob_time_sub': 'I’ll ask you in the morning how yesterday was. 15 seconds and you’re done.',
  'ob_time_label': 'Reminder at',
  'ob_time_change': 'Tap to change',
  'ob_circle_title': '…and as a circle.',
  'ob_circle_sub': 'Your year as a wheel. To share, or as a poster on the wall.',
  'ob_stats_title': 'Your patterns.',
  'ob_stats_sub': 'Which colours show up more often this month than last, and what happens especially often on which weekday.',
  'ob_corr_title': 'Maps on top of each other.',
  'ob_corr_sub': 'Pixi finds which colours belong together. Like restful nights and radiant days.',
  'ob_corr_add': 'Track a few more things right away to spot correlations.',
  'ob_corr_added': 'Added',
  'ob_go_title': 'All set, {name}.',
  'ob_go_sub': 'I’ll check in tomorrow morning. Promise.',
  'ob_go_notif': 'Allow reminders',
  'ob_time_notif': 'Turn on reminder',
  'ob_time_later': 'Maybe later',
  'ob_go_start': 'Let’s go',
  'ob_go_without': 'Start without reminder',

  'year_view': 'Year',
  'circle_view': 'Circle',
  'stats': 'Stats',
  'maps': 'Maps',
  'settings': 'Settings',
  'checkin': 'Check-in',
  'checkin_cta': 'How was yesterday?',
  'checkin_cta_today': 'How was today?',
  'checkin_done_today': 'Done for today ✓',
  'legend': 'Legend',
  'empty_year': 'Still empty. Tap a day or start the check-in.',
  'share': 'Share',
  'share_text': 'My year in pixels, painted with Pixi.',
  'day_title': 'How was the day?',
  'clear_entry': 'Clear entry',
  'no_maps_title': 'No map yet.',
  'no_maps_sub': 'Create your first map: mood, dreams, training …',
  'add_map': 'Add map',
  'days_filled': 'days logged',
  'streak': 'Streak',
  'streak_days': '{n} days',

  'ci_title': 'Good morning, {name}.',
  'ci_which_day': 'Which day?',
  'ci_summary_title': 'That’s it.',
  'ci_summary_sub': 'See you tomorrow morning.',
  'ci_skip_map': 'Not today',
  'ci_progress': '{a} of {b}',

  'maps_title': 'Your maps',
  'new_map': 'New map',
  'templates': 'Templates',
  'cat_feelings': 'Feelings',
  'cat_body': 'Body',
  'cat_habits': 'Habits',
  'cat_custom': 'Custom',
  'custom_map': 'Custom map',
  'custom_map_sub': 'Set your own question, colours and title',
  'edit_map': 'Edit map',
  'map_title_label': 'Title',
  'map_question_label': 'Morning question',
  'map_base_color': 'Base colour',
  'map_cat': 'Cat',
  'map_cat_sub': 'Who keeps you company on this map?',
  'cat_neutral': 'Neutral',
  'cat_stretch': 'Stretching',
  'cat_happy': 'Happy',
  'cat_wave': 'Waving',
  'cat_curious': 'Curious',
  'cat_gym': 'Workout',
  'cat_sleep': 'Sleeping',
  'cat_sad': 'Sad',
  'cat_bell': 'Alarm',
  'cat_dreams': 'Dreaming',
  'cat_period': 'Snuggled up',
  'cat_alcohol': 'With a cocktail',
  'cat_social': 'Cuddling',
  'cat_pain': 'In pain',
  'cat_screen': 'On the phone',
  'cat_gratitude': 'Grateful',
  'cat_energy': 'Energetic',
  'cat_anxiety': 'Anxious',
  'cat_reading': 'Reading',
  'cat_water': 'Drinking',
  'cat_meditation': 'Meditating',
  'this_month': 'This month',
  'this_month_sub': 'How often each colour, and the change from last month',
  'vs_last_month': 'vs last month',
  'month_no_data': 'Nothing logged this month yet.',
  'days_short': 'days',
  'ob_plan_title': 'Unlock all of Pixi?',
  'ob_plan_sub': 'Every map, all stats and links. The first 3 days are free.',
  'ob_plan_later': 'Start free for now',
  'ob_plan_cta': 'Unlock',
  'map_levels': 'Levels',
  'map_level_label': 'Label',
  'add_level': 'Add level',
  'delete_map': 'Delete map',
  'delete_map_confirm': 'Really delete? All entries of this map will be lost.',
  'free_limit_title': 'Four maps are free.',
  'free_limit_sub': 'Premium gives you unlimited maps, statistics and correlations.',
  'reorder_hint': 'Hold and drag to reorder',

  'stats_title': 'Statistics',
  'best_month': 'Best month',
  'worst_month': 'Weakest month',
  'best_weekday': 'Best weekday',
  'weakest_weekday': 'Weakest weekday',
  'average': 'Average',
  'distribution': 'Distribution',
  'per_month': 'Per month',
  'pw_prev_title': 'What Premium shows you',
  'pw_links_why': 'Find out what does you good: which colours show up together? Workout days and radiant moods, restless nights and grey days.',
  'pw_month_title': 'Your month in colours',
  'pw_month_why': 'See at a glance which colours show up more often this month than last.',
  'pw_week_title': 'Your weekly rhythm',
  'pw_week_why': 'Which weekday brings which colour? Small patterns, big effect.',
  'links_title': 'What goes together',
  'links_sub': 'Colours that show up on the same days far more often than chance. The 10 strongest across all your maps.',
  'links_none': 'No clear patterns yet. Log a few maps for a couple of weeks and you will see what goes together.',
  'correlations': 'Correlations',
  'corr_pick': 'Compare with',
  'corr_need_two': 'Correlations need at least two maps with entries on the same days.',
  'corr_none': 'No clear correlation yet. Give the maps a few weeks.',
  'corr_result_pos': 'On days with high “{a}”, “{b}” was {d} levels higher on average.',
  'corr_result_neg': 'On days with high “{a}”, “{b}” was {d} levels lower on average.',
  'corr_days': 'based on {n} shared days',
  'stats_locked_title': 'Statistics are Premium.',
  'stats_locked_sub': 'What goes together, your month compared with the last one, and your weekdays.',
  'not_enough_data': 'Not enough data yet. Log a few days.',

  'paywall_title': 'Pixi Premium',
  'paywall_sub': 'Try it free for 3 days, then cancel any month. Or pay once and keep Pixi forever.',
  'plan_year': 'Yearly',
  'plan_year_price': '\$14.99',
  'plan_year_sub': 'per year, cancel any time',
  'plan_life': 'Lifetime',
  'plan_life_price': '\$34.99',
  'plan_life_sub': 'pay once, yours forever',
  'feat_maps': 'Unlimited maps',
  'feat_stats': 'Statistics & correlations',
  'feat_support': 'Supports a small cat',
  'buy': 'Unlock',
  'restore': 'Restore purchases',
  'premium_active': 'Premium is active. Thank you!',
  'store_unavailable': 'The store is not reachable right now. Please try again later.',
  'restore_none': 'No previous purchases found.',
  'sub_disclosure': 'After the 3-day free trial the monthly plan renews automatically at {price} per month unless cancelled at least 24 hours before the end of the period in your Apple account settings. Payment is charged to your Apple account.',
  'terms': 'Terms of Use',
  'privacy': 'Privacy Policy',

  'reminder': 'Reminder',
  'reminder_time': 'Time',
  'reminder_on': 'Remind me in the morning',
  'your_name': 'Your name',
  'export': 'Export data',
  'about': 'About Pixi',
  'version': 'Version',
  'feedback': 'Send feedback',
  'rate': 'Rate Pixi',
  'dev_toggle_premium': 'Toggle Premium (test)',

  'fb_map_title': 'Quick question.',
  'fb_map_sub': 'How does Pixi feel so far?',
  'fb_checkin_title': 'First pixel placed!',
  'fb_checkin_sub': 'Was the check-in pleasant?',
  'fb_good': 'Good',
  'fb_meh': 'So-so',
  'fb_bad': 'Not really',
  'fb_thanks': 'Thanks, that helps.',
  'fb_tell': 'Care to tell us what could be better?',
  'fb_send': 'Send',

  't_mood': 'Mood',
  't_cry': 'Cried',
  't_anxiety': 'Anxiety',
  't_social': 'Social',
  't_gratitude': 'Grateful',
  't_dreams': 'Dreams',
  't_sleep': 'Sleep',
  't_energy': 'Energy',
  't_period': 'Period',
  't_pain': 'Pain',
  't_training': 'Training',
  't_alcohol': 'Alcohol',
  't_meditation': 'Meditation',
  't_reading': 'Reading',
  't_screen': 'Screen time',
  't_water': 'Water',

  'q_mood': 'How was your mood?',
  'q_cry': 'Did you cry?',
  'q_anxiety': 'How anxious were you?',
  'q_social': 'How much were you around people?',
  'q_gratitude': 'Anything you were grateful for?',
  'q_dreams': 'Did you dream?',
  'q_sleep': 'How did you sleep?',
  'q_energy': 'How much energy did you have?',
  'q_period': 'Period?',
  'q_pain': 'Were you in pain?',
  'q_training': 'Did you train?',
  'q_alcohol': 'Did you drink alcohol?',
  'q_meditation': 'Did you meditate?',
  'q_reading': 'Did you read?',
  'q_screen': 'How much screen time?',
  'q_water': 'Drank enough?',

  'l_mood_0': 'Stormy',
  'l_mood_1': 'Grey',
  'l_mood_2': 'Calm',
  'l_mood_3': 'Good',
  'l_mood_4': 'Radiant',
  'l_cry_0': 'Dry',
  'l_cry_1': 'Misty eyes',
  'l_cry_2': 'Cried',
  'l_cry_3': 'Waterfall',
  'l_anx_0': 'Zen',
  'l_anx_1': 'A bit nervous',
  'l_anx_2': 'Tense',
  'l_anx_3': 'Panic',
  'l_soc_0': 'Me-time',
  'l_soc_1': 'Quick chat',
  'l_soc_2': 'Good talks',
  'l_soc_3': 'Out & about',
  'l_gr_0': 'Not today',
  'l_gr_1': 'A little',
  'l_gr_2': 'Very grateful',
  'l_dr_0': 'None',
  'l_dr_1': 'Peaceful',
  'l_dr_2': 'Adventurous',
  'l_dr_3': 'Surreal',
  'l_dr_4': 'Romantic',
  'l_dr_5': 'Nightmare',
  'l_sl_0': 'Lay awake',
  'l_sl_1': 'Restless',
  'l_sl_2': 'Okay',
  'l_sl_3': 'Restful',
  'l_sl_4': 'Like a rock',
  'l_en_0': 'Battery empty',
  'l_en_1': 'Sluggish',
  'l_en_2': 'Awake',
  'l_en_3': 'Buzzing',
  'l_pe_0': 'None',
  'l_pe_1': 'Spotting',
  'l_pe_2': 'Light',
  'l_pe_3': 'Medium',
  'l_pe_4': 'Heavy',
  'l_pa_0': 'Pain-free',
  'l_pa_1': 'A twinge',
  'l_pa_2': 'Noticeable',
  'l_pa_3': 'Intense',
  'l_tr_0': 'Couch day',
  'l_tr_1': 'Walk',
  'l_tr_2': 'Workout',
  'l_tr_3': 'Beast mode',
  'l_al_0': 'Sober',
  'l_al_1': 'One glass',
  'l_al_2': 'Tipsy',
  'l_al_3': 'Hangover guaranteed',
  'l_me_0': 'Not today',
  'l_me_1': 'Short',
  'l_me_2': 'Deep',
  'l_rd_0': 'Nothing',
  'l_rd_1': 'A few pages',
  'l_rd_2': 'Absorbed',
  'l_sc_0': 'Digital detox',
  'l_sc_1': 'Normal',
  'l_sc_2': 'Too much',
  'l_sc_3': 'Doomscrolling',
  'l_wa_0': 'Parched',
  'l_wa_1': 'Okay',
  'l_wa_2': 'Well hydrated',
  'l_yes': 'Yes',
  'l_no': 'No',
  'l_low': 'Low',
  'l_mid': 'Medium',
  'l_high': 'High',

  'notif_title': 'How was yesterday, {name}?',
  'notif_body': 'One pixel, 15 seconds. Pixi is waiting.',
  'plan_month': 'Monthly',
  'plan_month_price': '\$12.99',
  'plan_month_sub': '3 days free, then {price} a month',
  'plan_month_sub_notrial': '{price} a month, cancel any time',
  'plan_trial_badge': '3 days free',
  'cta_trial': 'Try for free',
  'cta_life': 'Unlock forever',
  'day_short1': 'day',
  'pat_more': '{n} more “{l}” days',
  'pat_more1': '1 more “{l}” day',
  'pat_less': '{n} fewer “{l}” days',
  'pat_less1': '1 fewer “{l}” day',
  'pat_than': 'than in {m}.',
  'pat_same': 'Exactly the same colours as in {m}.',
  'pat_first_month': 'Your first month in colours.',
  'pat_week_title': 'Your weekdays',
  'pat_week_sub': 'Which colour shows up especially often on which weekday',
  'pat_week_line': 'On {wd}, “{l}” showed up especially often.',
  'pat_week_row': '“{l}” especially often',
  'pat_week_none': 'nothing stands out',
  'pat_year_title': 'Your year in colours',
  'ob_support_title': 'A small favour.',
  'ob_support_sub': 'I’m Caspar and I build Pixi all by myself. A rating from you would make my day and keeps me motivated to keep working on Pixi.',
  'ob_support_rate': 'Rate Pixi',
  'ob_support_skip': 'Not now',
  'fb_streak_title': '3 days in a row!',
  'fb_streak_sub': 'How do you like Pixi so far?',
  'follow_x': 'Follow me on X',
  'share_failed': 'Sharing didn’t work just now. Please try again.',
};
